# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proximadb/v1/sql.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proximadb/v1/sql.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proximadb_sdk.v1 import types_pb2 as proximadb_dot_v1_dot_types__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proximadb/v1/sql.proto\x12\x0cproximadb.v1\x1a\x18proximadb/v1/types.proto2]\n\nSqlService\x12O\n\nExecuteSql\x12\x1f.proximadb.v1.ExecuteSqlRequest\x1a .proximadb.v1.ExecuteSqlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proximadb.v1.sql_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SQLSERVICE']._serialized_start=66
  _globals['_SQLSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
