# ProximaDB Hierarchical Storage Configuration
# Demonstrates optimized storage layout with consistent mount points

[server]
node_id = "proximadb-node-1"
bind_address = "0.0.0.0"
port = 5678
data_dir = "/data/proximadb"

[storage]
# Legacy fields (deprecated, use storage_layout instead)
data_dirs = ["/data/proximadb"]
wal_dir = "/data/proximadb/wal"

# Storage engine configuration
mmap_enabled = true
cache_size_mb = 2048
bloom_filter_bits = 12

# LSM tree configuration
[storage.lsm_config]
memtable_size_mb = 64
level_count = 7
compaction_threshold = 4
block_size_kb = 64

# ProximaDB hierarchical storage layout
[storage.storage_layout]
node_instance = 1
assignment_strategy = "HashBased"

# Base storage paths (currently single disk, future multi-disk support)
[[storage.storage_layout.base_paths]]
base_dir = "/data/proximadb"
instance_id = 1
mount_point = "/data"
disk_type = { NvmeSsd = { max_iops = 100000 } }

# Capacity configuration
[storage.storage_layout.base_paths.capacity_config]
max_wal_size_mb = 1024        # 1GB per collection WAL
max_storage_size_mb = null    # Unlimited storage per collection
metadata_reserved_mb = 100    # 100MB reserved for metadata
warning_threshold_percent = 85.0

# Temp directory configuration
[storage.storage_layout.temp_config]
use_same_directory = true
temp_suffix = "___temp"
compaction_suffix = "___compaction"
flush_suffix = "___flushed"
cleanup_on_startup = true

# Filesystem optimization settings
[storage.filesystem_config]
enable_write_strategy_cache = true
temp_strategy = "SameDirectory"

# Atomic operations configuration
[storage.filesystem_config.atomic_config]
enable_local_atomic = true
enable_object_store_atomic = true
cleanup_temp_on_startup = true

# API configuration
[api]
grpc_port = 5679
rest_port = 5678
max_request_size_mb = 64
request_timeout_seconds = 30

# Monitoring configuration
[monitoring]
enabled = true
metrics_port = 9090
health_check_interval_seconds = 10

[monitoring.metrics]
collection_interval_seconds = 15
retention_hours = 168  # 7 days

# Consensus configuration (for distributed setups)
[consensus]
node_id = 1
election_timeout_ms = 5000
heartbeat_interval_ms = 1000

# Example: Future multi-disk configuration
# This shows how to configure multiple disks for increased I/O bandwidth
# Uncomment to enable multi-disk support

# [[storage.storage_layout.base_paths]]
# base_dir = "/data2/proximadb"
# instance_id = 2
# mount_point = "/data2"
# disk_type = { SataSsd = { max_iops = 50000 } }
# 
# [storage.storage_layout.base_paths.capacity_config]
# max_wal_size_mb = 1024
# max_storage_size_mb = null
# metadata_reserved_mb = 100
# warning_threshold_percent = 85.0

# [[storage.storage_layout.base_paths]]
# base_dir = "/data3/proximadb"
# instance_id = 3
# mount_point = "/data3"
# disk_type = { Hdd = { max_iops = 5000 } }
# 
# [storage.storage_layout.base_paths.capacity_config]
# max_wal_size_mb = 2048      # Larger WAL for slower disks
# max_storage_size_mb = null
# metadata_reserved_mb = 100
# warning_threshold_percent = 90.0