exclude = []

[report]
out = [ "Json", "Html", "Xml",]
follow-exec = true
implicit-test-threads = false
avoid-cfg-tarpaulin = true
exclude = []
skip-clean = true
timeout = "600s"
workspace = true
jobs = 20
release = true
all-features = false
default-features = true

[profile.release]
panic = "unwind"
debug = 2
all-targets = true
engine = "Llvm"
run-types = [ "Lib", "Tests",]
target-dir = "target/tarpaulin"
exclude-files = [ "clients/python/*",]
root = "."
