
[server]
node_id = "test-node-1"
bind_address = "0.0.0.0"
port = 5678
data_dir = "/workspace/test_data"

[storage]
data_dirs = ["/workspace/test_data"]
wal_dir = "/workspace/test_data/wal1"

[storage.wal_config]
wal_urls = [
    "file:///workspace/test_data/wal1",
    "file:///workspace/test_data/wal2", 
    "file:///workspace/test_data/wal3"
]
distribution_strategy = "RoundRobin"
collection_affinity = false
memory_flush_size_bytes = 1048576
global_flush_threshold = 2097152

[api]
grpc_port = 5679
rest_port = 5678
max_request_size_mb = 64
timeout_seconds = 30
enable_tls = false

[monitoring]
metrics_enabled = true
log_level = "debug"

[consensus]
node_id = 1
cluster_peers = []
election_timeout_ms = 5000
heartbeat_interval_ms = 1000
snapshot_threshold = 1000
