# Simple test configuration for ProximaDB
[server]
node_id = "test-node"
bind_address = "127.0.0.1"
port = 5678
grpc_port = 5679
data_dir = "/tmp/proximadb_test"

[storage]
data_dirs = ["/tmp/proximadb_test/data"]
wal_dir = "/tmp/proximadb_test/wal"
mmap_enabled = true
cache_size_mb = 256
bloom_filter_bits = 10

[storage.wal_config]
strategy_type = "Avro"
memtable_type = "BTree"
sync_mode = "PerBatch"
memory_flush_size_bytes = 1048576  # 1MB
batch_threshold = 100

[storage.lsm_config]
memtable_size_mb = 32
level_count = 4
compaction_threshold = 2
block_size_kb = 64

[logging]
level = "info"
file = "/tmp/proximadb_test/server.log"
EOF < /dev/null
