# ProximaDB 100k Vector Test - VIPER Engine with Avro WAL

[server]
node_id = "proximadb-100k-viper-avro"
bind_address = "127.0.0.1"
port = 5678
data_dir = "./test_100k_viper"

[storage]
# Legacy fields
data_dirs = ["./test_100k_viper"]
wal_dir = "./test_100k_viper/wal"

# Storage engine configuration
mmap_enabled = true
cache_size_mb = 512
bloom_filter_bits = 10

[storage.lsm_config]
memtable_size_mb = 64
level_count = 7
compaction_threshold = 4
block_size_kb = 32

# Avro WAL configuration for VIPER
[storage.wal_config]
wal_urls = ["file://./test_100k_viper/wal"]
strategy_type = "Avro"
memtable_type = "HashMap"
memory_flush_size_bytes = 1048576  # 1MB - trigger flush more frequently for 100k test
global_flush_threshold_bytes = 10485760  # 10MB
collection_affinity = true

# Storage layout for VIPER
[storage.storage_layout]
node_instance = 1
assignment_strategy = "HashBased"

[[storage.storage_layout.base_paths]]
base_dir = "./test_100k_viper/storage"
instance_id = 1
mount_point = "./test_100k_viper"
disk_type = { SataSsd = { max_iops = 50000 } }

[storage.storage_layout.base_paths.capacity_config]
max_wal_size_mb = 500
metadata_reserved_mb = 100
warning_threshold_percent = 85.0

[storage.storage_layout.temp_config]
use_same_directory = true
temp_suffix = "___temp"
compaction_suffix = "___compaction"
flush_suffix = "___flushed"
cleanup_on_startup = true

[storage.filesystem_config]
enable_write_strategy_cache = true
temp_strategy = "SameDirectory"

[storage.filesystem_config.atomic_config]
enable_local_atomic = true
enable_object_store_atomic = false
cleanup_temp_on_startup = true

# Metadata backend
[storage.metadata_backend]
backend_type = "filestore"
storage_url = "file://./test_100k_viper/metadata"
cache_size_mb = 64
flush_interval_secs = 10

[api]
grpc_port = 5679
rest_port = 5678
max_request_size_mb = 64  # Increased for batch operations
timeout_seconds = 120     # Increased timeout for large operations

[monitoring]
metrics_enabled = true
log_level = "info"

[consensus]
node_id = 1
cluster_peers = []
election_timeout_ms = 5000
heartbeat_interval_ms = 1000
snapshot_threshold = 1000