# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.affinity_response import AffinityResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    collection_id: str,
    *,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v2/collections/{collection_id}/affinity".format(
            collection_id=quote(str(collection_id), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> AffinityResponse | None:
    if response.status_code == 200:
        response_200 = AffinityResponse.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[AffinityResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[AffinityResponse]:
    r"""Read this node's cache-affinity entry for a collection.

     Returns `status: \"affinitized\"` (with query count, age, and a
    `stale` flag) when an entry exists — including stale entries,
    so operators can see which collections went cold — and
    `status: \"not_affinitized\"` when there is no entry at all.
    Routing has already stopped using stale entries.
    The optional `X-Tenant-ID` header is not consulted by this
    handler (the affinity registry is per-node, collection-keyed).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AffinityResponse]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> AffinityResponse | None:
    r"""Read this node's cache-affinity entry for a collection.

     Returns `status: \"affinitized\"` (with query count, age, and a
    `stale` flag) when an entry exists — including stale entries,
    so operators can see which collections went cold — and
    `status: \"not_affinitized\"` when there is no entry at all.
    Routing has already stopped using stale entries.
    The optional `X-Tenant-ID` header is not consulted by this
    handler (the affinity registry is per-node, collection-keyed).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AffinityResponse
    """

    return sync_detailed(
        collection_id=collection_id,
        client=client,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[AffinityResponse]:
    r"""Read this node's cache-affinity entry for a collection.

     Returns `status: \"affinitized\"` (with query count, age, and a
    `stale` flag) when an entry exists — including stale entries,
    so operators can see which collections went cold — and
    `status: \"not_affinitized\"` when there is no entry at all.
    Routing has already stopped using stale entries.
    The optional `X-Tenant-ID` header is not consulted by this
    handler (the affinity registry is per-node, collection-keyed).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AffinityResponse]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> AffinityResponse | None:
    r"""Read this node's cache-affinity entry for a collection.

     Returns `status: \"affinitized\"` (with query count, age, and a
    `stale` flag) when an entry exists — including stale entries,
    so operators can see which collections went cold — and
    `status: \"not_affinitized\"` when there is no entry at all.
    Routing has already stopped using stale entries.
    The optional `X-Tenant-ID` header is not consulted by this
    handler (the affinity registry is per-node, collection-keyed).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AffinityResponse
    """

    return (
        await asyncio_detailed(
            collection_id=collection_id,
            client=client,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
