//! Insight Generator
//!
//! Generates automated business insights from data analysis using AI.

use crate::ai::llm_integration::{LLMIntegrationEngine, LLMRequest};
use crate::ai::llm_integration::types::LLMRequestContext;
use crate::ai::business_intelligence::engine::{BusinessMetrics, QueryResult};
use super::trend_analyzer::TrendAnalysis;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use chrono::{DateTime, Utc};
use anyhow::Result;
use tracing::{debug, info};

/// Insight generator for automated business intelligence
#[derive(Clone)]
pub struct InsightGenerator {
    llm_engine: Arc<LLMIntegrationEngine>,
    config: InsightGeneratorConfig,
}

/// Configuration for insight generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InsightGeneratorConfig {
    pub min_confidence_threshold: f32,
    pub max_insights_per_analysis: usize,
    pub enable_predictive_insights: bool,
    pub enable_comparative_analysis: bool,
}

/// Business insight generated by AI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BusinessInsight {
    pub insight_id: String,
    pub title: String,
    pub description: String,
    pub insight_type: InsightType,
    pub confidence_score: f32,
    pub impact_score: f32,
    pub data_source: String,
    pub generated_at: DateTime<Utc>,
    pub recommendations: Vec<String>,
    pub supporting_data: Vec<String>,
}

/// Types of business insights
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum InsightType {
    TrendIdentification,
    AnomalyDetection,
    PerformanceOptimization,
    CustomerBehavior,
    RevenueOpportunity,
    OperationalEfficiency,
    RiskAssessment,
    CompetitiveAnalysis,
}

impl InsightGenerator {
    pub async fn new(llm_engine: Arc<LLMIntegrationEngine>) -> Result<Self> {
        let config = InsightGeneratorConfig::default();

        Ok(Self {
            llm_engine,
            config,
        })
    }

    /// Generate business insights from metrics and trends
    pub async fn generate_business_insights(
        &self,
        metrics: &BusinessMetrics,
        trends: &[TrendAnalysis],
    ) -> Result<Vec<BusinessInsight>> {
        info!("Generating business insights from {} trends", trends.len());

        let mut insights = Vec::new();

        // Generate insights from revenue metrics
        if let Some(revenue_insights) = self.analyze_revenue_metrics(&metrics.revenue_metrics).await? {
            insights.extend(revenue_insights);
        }

        // Generate insights from customer metrics
        if let Some(customer_insights) = self.analyze_customer_metrics(&metrics.customer_metrics).await? {
            insights.extend(customer_insights);
        }

        // Generate insights from operational metrics
        if let Some(operational_insights) = self.analyze_operational_metrics(&metrics.operational_metrics).await? {
            insights.extend(operational_insights);
        }

        // Generate insights from performance metrics
        if let Some(performance_insights) = self.analyze_performance_metrics(&metrics.performance_metrics).await? {
            insights.extend(performance_insights);
        }

        // Generate insights from trend analysis
        for trend in trends {
            if let Some(trend_insight) = self.generate_trend_insight(trend).await? {
                insights.push(trend_insight);
            }
        }

        // Filter by confidence threshold
        insights.retain(|insight| insight.confidence_score >= self.config.min_confidence_threshold);

        // Limit number of insights
        insights.truncate(self.config.max_insights_per_analysis);

        // Sort by impact score
        insights.sort_by(|a, b| b.impact_score.partial_cmp(&a.impact_score).unwrap_or(std::cmp::Ordering::Equal));

        info!("Generated {} business insights", insights.len());
        Ok(insights)
    }

    /// Analyze revenue metrics for insights
    async fn analyze_revenue_metrics(&self, revenue: &super::engine::RevenueMetrics) -> Result<Option<Vec<BusinessInsight>>> {
        if revenue.total_revenue.is_none() && revenue.revenue_growth_percent.is_none() {
            return Ok(None);
        }

        let mut insights = Vec::new();

        // Revenue growth insight
        if let Some(growth_rate) = revenue.revenue_growth_percent {
            let insight = self.generate_revenue_growth_insight(growth_rate).await?;
            insights.push(insight);
        }

        // Revenue per customer insight
        if let (Some(total_revenue), Some(avg_per_customer)) = (revenue.total_revenue, revenue.avg_revenue_per_customer) {
            if avg_per_customer > 0.0 {
                let customer_count = (total_revenue / avg_per_customer) as u64;
                let insight = self.generate_customer_value_insight(avg_per_customer, customer_count).await?;
                insights.push(insight);
            }
        }

        Ok(Some(insights))
    }

    /// Generate revenue growth insight
    async fn generate_revenue_growth_insight(&self, growth_rate: f64) -> Result<BusinessInsight> {
        let (title, description, impact_score) = match growth_rate {
            g if g > 20.0 => (
                "Exceptional Revenue Growth".to_string(),
                format!("Revenue is growing at {:.1}% - significantly above industry average", g),
                0.9
            ),
            g if g > 10.0 => (
                "Strong Revenue Growth".to_string(),
                format!("Revenue growth of {:.1}% indicates healthy business expansion", g),
                0.8
            ),
            g if g > 0.0 => (
                "Positive Revenue Trend".to_string(),
                format!("Revenue growing at {:.1}% - continue current strategies", g),
                0.6
            ),
            g if g > -5.0 => (
                "Revenue Decline Warning".to_string(),
                format!("Revenue declining at {:.1}% - requires immediate attention", g.abs()),
                0.7
            ),
            g => (
                "Critical Revenue Decline".to_string(),
                format!("Severe revenue decline of {:.1}% - emergency intervention needed", g.abs()),
                0.95
            ),
        };

        Ok(BusinessInsight {
            insight_id: uuid::Uuid::new_v4().to_string(),
            title,
            description,
            insight_type: InsightType::RevenueOpportunity,
            confidence_score: 0.9,
            impact_score,
            data_source: "Revenue Metrics Analysis".to_string(),
            generated_at: Utc::now(),
            recommendations: self.generate_revenue_recommendations(growth_rate),
            supporting_data: vec![format!("Revenue Growth Rate: {:.1}%", growth_rate)],
        })
    }

    /// Generate customer value insight
    async fn generate_customer_value_insight(&self, avg_revenue_per_customer: f64, customer_count: u64) -> Result<BusinessInsight> {
        let insight = BusinessInsight {
            insight_id: uuid::Uuid::new_v4().to_string(),
            title: "Customer Value Analysis".to_string(),
            description: format!(
                "Average revenue per customer is ${:.2} across {} customers",
                avg_revenue_per_customer, customer_count
            ),
            insight_type: InsightType::CustomerBehavior,
            confidence_score: 0.85,
            impact_score: 0.7,
            data_source: "Customer Revenue Analysis".to_string(),
            generated_at: Utc::now(),
            recommendations: vec![
                "Focus on high-value customer retention".to_string(),
                "Develop upselling strategies for existing customers".to_string(),
            ],
            supporting_data: vec![
                format!("Avg Revenue/Customer: ${:.2}", avg_revenue_per_customer),
                format!("Total Customers: {}", customer_count),
            ],
        };

        Ok(insight)
    }

    /// Generate recommendations for revenue trends
    fn generate_revenue_recommendations(&self, growth_rate: f64) -> Vec<String> {
        match growth_rate {
            g if g > 20.0 => vec![
                "Scale operations to support continued growth".to_string(),
                "Invest in infrastructure expansion".to_string(),
                "Consider new market opportunities".to_string(),
            ],
            g if g > 10.0 => vec![
                "Maintain current growth strategies".to_string(),
                "Monitor for scaling bottlenecks".to_string(),
                "Optimize customer acquisition".to_string(),
            ],
            g if g > 0.0 => vec![
                "Analyze growth opportunities".to_string(),
                "Improve customer retention".to_string(),
                "Optimize pricing strategies".to_string(),
            ],
            g if g > -10.0 => vec![
                "Immediate review of declining metrics".to_string(),
                "Identify root causes of decline".to_string(),
                "Implement corrective measures".to_string(),
            ],
            _ => vec![
                "Emergency revenue recovery plan needed".to_string(),
                "Comprehensive business strategy review".to_string(),
                "Consider strategic partnerships or pivots".to_string(),
            ],
        }
    }

    /// Analyze customer metrics for insights
    async fn analyze_customer_metrics(&self, _customer: &super::engine::CustomerMetrics) -> Result<Option<Vec<BusinessInsight>>> {
        // Placeholder implementation
        Ok(None)
    }

    /// Analyze operational metrics for insights
    async fn analyze_operational_metrics(&self, _operational: &super::engine::OperationalMetrics) -> Result<Option<Vec<BusinessInsight>>> {
        // Placeholder implementation
        Ok(None)
    }

    /// Analyze performance metrics for insights
    async fn analyze_performance_metrics(&self, _performance: &super::engine::PerformanceMetrics) -> Result<Option<Vec<BusinessInsight>>> {
        // Placeholder implementation
        Ok(None)
    }

    /// Generate insight from trend analysis
    async fn generate_trend_insight(&self, trend: &TrendAnalysis) -> Result<Option<BusinessInsight>> {
        if trend.confidence_score < 0.7 {
            return Ok(None);
        }

        let insight = BusinessInsight {
            insight_id: uuid::Uuid::new_v4().to_string(),
            title: format!("{} Trend Detected", trend.metric_name),
            description: format!(
                "Trend analysis shows {} trend with {:.1}% change over {} period",
                trend.direction, trend.change_percentage, trend.time_period
            ),
            insight_type: InsightType::TrendIdentification,
            confidence_score: trend.confidence_score,
            impact_score: (trend.change_percentage.abs() / 100.0).min(1.0) as f32,
            data_source: "Trend Analysis".to_string(),
            generated_at: Utc::now(),
            recommendations: vec![
                format!("Monitor {} trend closely", trend.metric_name),
                "Analyze underlying drivers".to_string(),
            ],
            supporting_data: vec![
                format!("Change: {:.1}%", trend.change_percentage),
                format!("Confidence: {:.1}%", trend.confidence_score * 100.0),
            ],
        };

        Ok(Some(insight))
    }
}

impl Default for InsightGeneratorConfig {
    fn default() -> Self {
        Self {
            min_confidence_threshold: 0.7,
            max_insights_per_analysis: 15,
            enable_predictive_insights: true,
            enable_comparative_analysis: true,
        }
    }
}