# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.unified_bare_error import UnifiedBareError
from ...types import UNSET, Response, Unset


def _get_kwargs(
    statement_id: str,
    *,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/api/v2/unified/prepared/{statement_id}".format(
            statement_id=quote(str(statement_id), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | UnifiedBareError | None:
    if response.status_code == 204:
        response_204 = cast(Any, None)
        return response_204

    if response.status_code == 500:
        response_500 = UnifiedBareError.from_dict(response.json())

        return response_500

    if response.status_code == 501:
        response_501 = UnifiedBareError.from_dict(response.json())

        return response_501

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | UnifiedBareError]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    statement_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[Any | UnifiedBareError]:
    """Delete a prepared statement.

     The optional `X-Tenant-ID` header is not consulted by this
    handler — unified queries run without tenant selection.

    Args:
        statement_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | UnifiedBareError]
    """

    kwargs = _get_kwargs(
        statement_id=statement_id,
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    statement_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Any | UnifiedBareError | None:
    """Delete a prepared statement.

     The optional `X-Tenant-ID` header is not consulted by this
    handler — unified queries run without tenant selection.

    Args:
        statement_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | UnifiedBareError
    """

    return sync_detailed(
        statement_id=statement_id,
        client=client,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    statement_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[Any | UnifiedBareError]:
    """Delete a prepared statement.

     The optional `X-Tenant-ID` header is not consulted by this
    handler — unified queries run without tenant selection.

    Args:
        statement_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | UnifiedBareError]
    """

    kwargs = _get_kwargs(
        statement_id=statement_id,
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    statement_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Any | UnifiedBareError | None:
    """Delete a prepared statement.

     The optional `X-Tenant-ID` header is not consulted by this
    handler — unified queries run without tenant selection.

    Args:
        statement_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | UnifiedBareError
    """

    return (
        await asyncio_detailed(
            statement_id=statement_id,
            client=client,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
