# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.abac_attr_value_type_0 import AbacAttrValueType0
    from ..models.abac_attr_value_type_1 import AbacAttrValueType1
    from ..models.abac_attr_value_type_2 import AbacAttrValueType2
    from ..models.abac_attr_value_type_3 import AbacAttrValueType3


T = TypeVar("T", bound="AbacAttributeBindingAttrs")


@_attrs_define
class AbacAttributeBindingAttrs:
    """ """

    additional_properties: dict[
        str,
        AbacAttrValueType0
        | AbacAttrValueType1
        | AbacAttrValueType2
        | AbacAttrValueType3,
    ] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.abac_attr_value_type_0 import AbacAttrValueType0
        from ..models.abac_attr_value_type_1 import AbacAttrValueType1
        from ..models.abac_attr_value_type_2 import AbacAttrValueType2
        from ..models.abac_attr_value_type_3 import AbacAttrValueType3

        field_dict: dict[str, Any] = {}
        for prop_name, prop in self.additional_properties.items():

            if isinstance(prop, AbacAttrValueType0):
                field_dict[prop_name] = prop.to_dict()
            elif isinstance(prop, AbacAttrValueType1):
                field_dict[prop_name] = prop.to_dict()
            elif isinstance(prop, AbacAttrValueType2):
                field_dict[prop_name] = prop.to_dict()
            else:
                field_dict[prop_name] = prop.to_dict()

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.abac_attr_value_type_0 import AbacAttrValueType0
        from ..models.abac_attr_value_type_1 import AbacAttrValueType1
        from ..models.abac_attr_value_type_2 import AbacAttrValueType2
        from ..models.abac_attr_value_type_3 import AbacAttrValueType3

        d = dict(src_dict)
        abac_attribute_binding_attrs = cls()

        additional_properties = {}
        for prop_name, prop_dict in d.items():

            def _parse_additional_property(
                data: object,
            ) -> (
                AbacAttrValueType0
                | AbacAttrValueType1
                | AbacAttrValueType2
                | AbacAttrValueType3
            ):
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    componentsschemas_abac_attr_value_type_0 = (
                        AbacAttrValueType0.from_dict(data)
                    )

                    return componentsschemas_abac_attr_value_type_0
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    componentsschemas_abac_attr_value_type_1 = (
                        AbacAttrValueType1.from_dict(data)
                    )

                    return componentsschemas_abac_attr_value_type_1
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    componentsschemas_abac_attr_value_type_2 = (
                        AbacAttrValueType2.from_dict(data)
                    )

                    return componentsschemas_abac_attr_value_type_2
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_abac_attr_value_type_3 = AbacAttrValueType3.from_dict(
                    data
                )

                return componentsschemas_abac_attr_value_type_3

            additional_property = _parse_additional_property(prop_dict)

            additional_properties[prop_name] = additional_property

        abac_attribute_binding_attrs.additional_properties = additional_properties
        return abac_attribute_binding_attrs

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(
        self, key: str
    ) -> (
        AbacAttrValueType0
        | AbacAttrValueType1
        | AbacAttrValueType2
        | AbacAttrValueType3
    ):
        return self.additional_properties[key]

    def __setitem__(
        self,
        key: str,
        value: (
            AbacAttrValueType0
            | AbacAttrValueType1
            | AbacAttrValueType2
            | AbacAttrValueType3
        ),
    ) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
