# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.append_model_evidence_mutation import AppendModelEvidenceMutation
    from ..models.catalog_model_registry_mutation_type_1 import (
        CatalogModelRegistryMutationType1,
    )
    from ..models.record_model_decision_mutation import RecordModelDecisionMutation
    from ..models.register_model_version_mutation import RegisterModelVersionMutation
    from ..models.upsert_model_deployment_mutation import UpsertModelDeploymentMutation


T = TypeVar("T", bound="ApplyModelRegistryMutationRequest")


@_attrs_define
class ApplyModelRegistryMutationRequest:
    """
    Attributes:
        expected_revision (int): Optimistic concurrency token returned by the previous read or mutation.
        mutation (AppendModelEvidenceMutation | CatalogModelRegistryMutationType1 | RecordModelDecisionMutation |
            RegisterModelVersionMutation | UpsertModelDeploymentMutation): Command-shaped mutations preserve
            version/evidence/decision immutability at
            the persistence boundary. API adapters lower into these commands instead
            of replacing a whole registry document.
    """

    expected_revision: int
    mutation: AppendModelEvidenceMutation | CatalogModelRegistryMutationType1 | RecordModelDecisionMutation | RegisterModelVersionMutation | UpsertModelDeploymentMutation
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.append_model_evidence_mutation import AppendModelEvidenceMutation
        from ..models.catalog_model_registry_mutation_type_1 import (
            CatalogModelRegistryMutationType1,
        )
        from ..models.record_model_decision_mutation import RecordModelDecisionMutation
        from ..models.register_model_version_mutation import (
            RegisterModelVersionMutation,
        )
        from ..models.upsert_model_deployment_mutation import (
            UpsertModelDeploymentMutation,
        )

        expected_revision = self.expected_revision

        mutation: dict[str, Any]
        if isinstance(self.mutation, RegisterModelVersionMutation):
            mutation = self.mutation.to_dict()
        elif isinstance(self.mutation, CatalogModelRegistryMutationType1):
            mutation = self.mutation.to_dict()
        elif isinstance(self.mutation, AppendModelEvidenceMutation):
            mutation = self.mutation.to_dict()
        elif isinstance(self.mutation, RecordModelDecisionMutation):
            mutation = self.mutation.to_dict()
        else:
            mutation = self.mutation.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "expected_revision": expected_revision,
                "mutation": mutation,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.append_model_evidence_mutation import AppendModelEvidenceMutation
        from ..models.catalog_model_registry_mutation_type_1 import (
            CatalogModelRegistryMutationType1,
        )
        from ..models.record_model_decision_mutation import RecordModelDecisionMutation
        from ..models.register_model_version_mutation import (
            RegisterModelVersionMutation,
        )
        from ..models.upsert_model_deployment_mutation import (
            UpsertModelDeploymentMutation,
        )

        d = dict(src_dict)
        expected_revision = d.pop("expected_revision")

        def _parse_mutation(
            data: object,
        ) -> (
            AppendModelEvidenceMutation
            | CatalogModelRegistryMutationType1
            | RecordModelDecisionMutation
            | RegisterModelVersionMutation
            | UpsertModelDeploymentMutation
        ):
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_catalog_model_registry_mutation_register_model_version_mutation = RegisterModelVersionMutation.from_dict(
                    data
                )

                return componentsschemas_catalog_model_registry_mutation_register_model_version_mutation
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_catalog_model_registry_mutation_type_1 = (
                    CatalogModelRegistryMutationType1.from_dict(data)
                )

                return componentsschemas_catalog_model_registry_mutation_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_catalog_model_registry_mutation_append_model_evidence_mutation = AppendModelEvidenceMutation.from_dict(
                    data
                )

                return componentsschemas_catalog_model_registry_mutation_append_model_evidence_mutation
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_catalog_model_registry_mutation_record_model_decision_mutation = RecordModelDecisionMutation.from_dict(
                    data
                )

                return componentsschemas_catalog_model_registry_mutation_record_model_decision_mutation
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            if not isinstance(data, dict):
                raise TypeError()
            componentsschemas_catalog_model_registry_mutation_upsert_model_deployment_mutation = UpsertModelDeploymentMutation.from_dict(
                data
            )

            return componentsschemas_catalog_model_registry_mutation_upsert_model_deployment_mutation

        mutation = _parse_mutation(d.pop("mutation"))

        apply_model_registry_mutation_request = cls(
            expected_revision=expected_revision,
            mutation=mutation,
        )

        apply_model_registry_mutation_request.additional_properties = d
        return apply_model_registry_mutation_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
