# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.canonical_node_properties import CanonicalNodeProperties
    from ..models.graph_embedding import GraphEmbedding


T = TypeVar("T", bound="CanonicalNode")


@_attrs_define
class CanonicalNode:
    """
    Attributes:
        id (str):
        labels (list[str]):
        properties (CanonicalNodeProperties):
        created_at (str):
        updated_at (str):
        embedding (GraphEmbedding | Unset):
    """

    id: str
    labels: list[str]
    properties: CanonicalNodeProperties
    created_at: str
    updated_at: str
    embedding: GraphEmbedding | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.canonical_node_properties import CanonicalNodeProperties
        from ..models.graph_embedding import GraphEmbedding

        id = self.id

        labels = self.labels

        properties = self.properties.to_dict()

        created_at = self.created_at

        updated_at = self.updated_at

        embedding: dict[str, Any] | Unset = UNSET
        if not isinstance(self.embedding, Unset):
            embedding = self.embedding.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "labels": labels,
                "properties": properties,
                "created_at": created_at,
                "updated_at": updated_at,
            }
        )
        if embedding is not UNSET:
            field_dict["embedding"] = embedding

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.canonical_node_properties import CanonicalNodeProperties
        from ..models.graph_embedding import GraphEmbedding

        d = dict(src_dict)
        id = d.pop("id")

        labels = cast(list[str], d.pop("labels"))

        properties = CanonicalNodeProperties.from_dict(d.pop("properties"))

        created_at = d.pop("created_at")

        updated_at = d.pop("updated_at")

        _embedding = d.pop("embedding", UNSET)
        embedding: GraphEmbedding | Unset
        if isinstance(_embedding, Unset):
            embedding = UNSET
        else:
            embedding = GraphEmbedding.from_dict(_embedding)

        canonical_node = cls(
            id=id,
            labels=labels,
            properties=properties,
            created_at=created_at,
            updated_at=updated_at,
            embedding=embedding,
        )

        canonical_node.additional_properties = d
        return canonical_node

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
