# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.capabilities_response_error_envelope import (
        CapabilitiesResponseErrorEnvelope,
    )
    from ..models.capabilities_response_limits import CapabilitiesResponseLimits


T = TypeVar("T", bound="CapabilitiesResponse")


@_attrs_define
class CapabilitiesResponse:
    """
    Attributes:
        api_version (Union[Unset, str]):
        error_envelope (Union[Unset, CapabilitiesResponseErrorEnvelope]):
        features (Union[Unset, list[str]]):
        limits (Union[Unset, CapabilitiesResponseLimits]):
        surface (Union[Unset, str]):
    """

    api_version: Union[Unset, str] = UNSET
    error_envelope: Union[Unset, "CapabilitiesResponseErrorEnvelope"] = UNSET
    features: Union[Unset, list[str]] = UNSET
    limits: Union[Unset, "CapabilitiesResponseLimits"] = UNSET
    surface: Union[Unset, str] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.capabilities_response_error_envelope import (
            CapabilitiesResponseErrorEnvelope,
        )
        from ..models.capabilities_response_limits import CapabilitiesResponseLimits

        api_version = self.api_version

        error_envelope: Union[Unset, dict[str, Any]] = UNSET
        if not isinstance(self.error_envelope, Unset):
            error_envelope = self.error_envelope.to_dict()

        features: Union[Unset, list[str]] = UNSET
        if not isinstance(self.features, Unset):
            features = self.features

        limits: Union[Unset, dict[str, Any]] = UNSET
        if not isinstance(self.limits, Unset):
            limits = self.limits.to_dict()

        surface = self.surface

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if api_version is not UNSET:
            field_dict["api_version"] = api_version
        if error_envelope is not UNSET:
            field_dict["error_envelope"] = error_envelope
        if features is not UNSET:
            field_dict["features"] = features
        if limits is not UNSET:
            field_dict["limits"] = limits
        if surface is not UNSET:
            field_dict["surface"] = surface

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.capabilities_response_error_envelope import (
            CapabilitiesResponseErrorEnvelope,
        )
        from ..models.capabilities_response_limits import CapabilitiesResponseLimits

        d = dict(src_dict)
        api_version = d.pop("api_version", UNSET)

        _error_envelope = d.pop("error_envelope", UNSET)
        error_envelope: Union[Unset, CapabilitiesResponseErrorEnvelope]
        if isinstance(_error_envelope, Unset):
            error_envelope = UNSET
        else:
            error_envelope = CapabilitiesResponseErrorEnvelope.from_dict(
                _error_envelope
            )

        features = cast(list[str], d.pop("features", UNSET))

        _limits = d.pop("limits", UNSET)
        limits: Union[Unset, CapabilitiesResponseLimits]
        if isinstance(_limits, Unset):
            limits = UNSET
        else:
            limits = CapabilitiesResponseLimits.from_dict(_limits)

        surface = d.pop("surface", UNSET)

        capabilities_response = cls(
            api_version=api_version,
            error_envelope=error_envelope,
            features=features,
            limits=limits,
            surface=surface,
        )

        capabilities_response.additional_properties = d
        return capabilities_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
