# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.catalog_embedding_input_contract_document_parameters import (
        CatalogEmbeddingInputContractDocumentParameters,
    )
    from ..models.catalog_embedding_input_contract_query_parameters import (
        CatalogEmbeddingInputContractQueryParameters,
    )


T = TypeVar("T", bound="CatalogEmbeddingInputContract")


@_attrs_define
class CatalogEmbeddingInputContract:
    """Exact rendered-input and tokenizer budget consumed by an embedding runtime.

    Attributes:
        declared_context_limit (int):
        document_template (str):
        effective_context_limit (int):
        model_revision (str):
        query_template (str):
        special_token_count (int):
        tokenizer_fingerprint (str):
        tokenizer_id (str):
        tokenizer_revision (str):
        document_parameters (CatalogEmbeddingInputContractDocumentParameters | Unset):
        query_parameters (CatalogEmbeddingInputContractQueryParameters | Unset):
    """

    declared_context_limit: int
    document_template: str
    effective_context_limit: int
    model_revision: str
    query_template: str
    special_token_count: int
    tokenizer_fingerprint: str
    tokenizer_id: str
    tokenizer_revision: str
    document_parameters: CatalogEmbeddingInputContractDocumentParameters | Unset = UNSET
    query_parameters: CatalogEmbeddingInputContractQueryParameters | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.catalog_embedding_input_contract_document_parameters import (
            CatalogEmbeddingInputContractDocumentParameters,
        )
        from ..models.catalog_embedding_input_contract_query_parameters import (
            CatalogEmbeddingInputContractQueryParameters,
        )

        declared_context_limit = self.declared_context_limit

        document_template = self.document_template

        effective_context_limit = self.effective_context_limit

        model_revision = self.model_revision

        query_template = self.query_template

        special_token_count = self.special_token_count

        tokenizer_fingerprint = self.tokenizer_fingerprint

        tokenizer_id = self.tokenizer_id

        tokenizer_revision = self.tokenizer_revision

        document_parameters: dict[str, Any] | Unset = UNSET
        if not isinstance(self.document_parameters, Unset):
            document_parameters = self.document_parameters.to_dict()

        query_parameters: dict[str, Any] | Unset = UNSET
        if not isinstance(self.query_parameters, Unset):
            query_parameters = self.query_parameters.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "declared_context_limit": declared_context_limit,
                "document_template": document_template,
                "effective_context_limit": effective_context_limit,
                "model_revision": model_revision,
                "query_template": query_template,
                "special_token_count": special_token_count,
                "tokenizer_fingerprint": tokenizer_fingerprint,
                "tokenizer_id": tokenizer_id,
                "tokenizer_revision": tokenizer_revision,
            }
        )
        if document_parameters is not UNSET:
            field_dict["document_parameters"] = document_parameters
        if query_parameters is not UNSET:
            field_dict["query_parameters"] = query_parameters

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.catalog_embedding_input_contract_document_parameters import (
            CatalogEmbeddingInputContractDocumentParameters,
        )
        from ..models.catalog_embedding_input_contract_query_parameters import (
            CatalogEmbeddingInputContractQueryParameters,
        )

        d = dict(src_dict)
        declared_context_limit = d.pop("declared_context_limit")

        document_template = d.pop("document_template")

        effective_context_limit = d.pop("effective_context_limit")

        model_revision = d.pop("model_revision")

        query_template = d.pop("query_template")

        special_token_count = d.pop("special_token_count")

        tokenizer_fingerprint = d.pop("tokenizer_fingerprint")

        tokenizer_id = d.pop("tokenizer_id")

        tokenizer_revision = d.pop("tokenizer_revision")

        _document_parameters = d.pop("document_parameters", UNSET)
        document_parameters: CatalogEmbeddingInputContractDocumentParameters | Unset
        if isinstance(_document_parameters, Unset):
            document_parameters = UNSET
        else:
            document_parameters = (
                CatalogEmbeddingInputContractDocumentParameters.from_dict(
                    _document_parameters
                )
            )

        _query_parameters = d.pop("query_parameters", UNSET)
        query_parameters: CatalogEmbeddingInputContractQueryParameters | Unset
        if isinstance(_query_parameters, Unset):
            query_parameters = UNSET
        else:
            query_parameters = CatalogEmbeddingInputContractQueryParameters.from_dict(
                _query_parameters
            )

        catalog_embedding_input_contract = cls(
            declared_context_limit=declared_context_limit,
            document_template=document_template,
            effective_context_limit=effective_context_limit,
            model_revision=model_revision,
            query_template=query_template,
            special_token_count=special_token_count,
            tokenizer_fingerprint=tokenizer_fingerprint,
            tokenizer_id=tokenizer_id,
            tokenizer_revision=tokenizer_revision,
            document_parameters=document_parameters,
            query_parameters=query_parameters,
        )

        catalog_embedding_input_contract.additional_properties = d
        return catalog_embedding_input_contract

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
