# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="CatalogArtifactDescriptor")


@_attrs_define
class CatalogArtifactDescriptor:
    """Content-addressed reference to bytes held outside xCatalog.

    Attributes:
        digest (str):
        media_type (str):
        size_bytes (int):
        uri (str):
    """

    digest: str
    media_type: str
    size_bytes: int
    uri: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        digest = self.digest

        media_type = self.media_type

        size_bytes = self.size_bytes

        uri = self.uri

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "digest": digest,
                "media_type": media_type,
                "size_bytes": size_bytes,
                "uri": uri,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        digest = d.pop("digest")

        media_type = d.pop("media_type")

        size_bytes = d.pop("size_bytes")

        uri = d.pop("uri")

        catalog_artifact_descriptor = cls(
            digest=digest,
            media_type=media_type,
            size_bytes=size_bytes,
            uri=uri,
        )

        catalog_artifact_descriptor.additional_properties = d
        return catalog_artifact_descriptor

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
