# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="FusionSearchRequest")


@_attrs_define
class FusionSearchRequest:
    """
    Attributes:
        query_vector (list[float]): Query embedding for the ANN seed.
        vector_collection (str): Vector collection to seed from (its records co-indexed with this graph by `oid`).
        consensus_beta (Union[None, Unset, float]): Consensus boost added to any `oid` present in ≥2 sources.
        document_collection (Union[None, Unset, str]): Collection whose document index to BM25-search. Defaults to
            `vector_collection` (documents
            co-indexed with the vectors share the record `oid`, so they merge by `oid`).
        document_weight (Union[None, Unset, float]): Document modality weight (mirrors `vector_weight` /
            `graph_weight`). Defaults to 1.0.
        edge_types (Union[Unset, list[str]]):
        grain (Union[None, Unset, str]): Graph contribution grain: `"nodes"` (default), `"edges"`, or `"both"`.
        graph_weight (Union[None, Unset, float]):
        limit (Union[Unset, int]):
        max_depth (Union[Unset, int]): k-hop expansion depth (bounded; default 1 — the validated sweet spot).
        max_seeds (Union[Unset, int]): How many of the top vector seeds to expand from (bounded expansion).
        min_weight_fraction (Union[None, Unset, float]): Cost-routing policy inputs (TD-141): drop negligible modalities
            (weight fraction) and budget each.
            When absent, fusion is unbounded.
        rrf (Union[Unset, bool]): Use the rank-based RRF fallback instead of PIT-calibrated linear.
        text_query (Union[None, Unset, str]): Optional BM25/full-text query (TD-138). When present (and non-empty),
            fusion also searches the
            collection's document index and merges BM25 hits into the result by shared `oid` — tri-modal
            (vector + graph + document) fusion. Absent ⇒ vector+graph only (unchanged).
        total_budget (Union[None, Unset, int]):
        vector_weight (Union[None, Unset, float]):
    """

    query_vector: list[float]
    vector_collection: str
    consensus_beta: Union[None, Unset, float] = UNSET
    document_collection: Union[None, Unset, str] = UNSET
    document_weight: Union[None, Unset, float] = UNSET
    edge_types: Union[Unset, list[str]] = UNSET
    grain: Union[None, Unset, str] = UNSET
    graph_weight: Union[None, Unset, float] = UNSET
    limit: Union[Unset, int] = UNSET
    max_depth: Union[Unset, int] = UNSET
    max_seeds: Union[Unset, int] = UNSET
    min_weight_fraction: Union[None, Unset, float] = UNSET
    rrf: Union[Unset, bool] = UNSET
    text_query: Union[None, Unset, str] = UNSET
    total_budget: Union[None, Unset, int] = UNSET
    vector_weight: Union[None, Unset, float] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        query_vector = self.query_vector

        vector_collection = self.vector_collection

        consensus_beta: Union[None, Unset, float]
        if isinstance(self.consensus_beta, Unset):
            consensus_beta = UNSET
        else:
            consensus_beta = self.consensus_beta

        document_collection: Union[None, Unset, str]
        if isinstance(self.document_collection, Unset):
            document_collection = UNSET
        else:
            document_collection = self.document_collection

        document_weight: Union[None, Unset, float]
        if isinstance(self.document_weight, Unset):
            document_weight = UNSET
        else:
            document_weight = self.document_weight

        edge_types: Union[Unset, list[str]] = UNSET
        if not isinstance(self.edge_types, Unset):
            edge_types = self.edge_types

        grain: Union[None, Unset, str]
        if isinstance(self.grain, Unset):
            grain = UNSET
        else:
            grain = self.grain

        graph_weight: Union[None, Unset, float]
        if isinstance(self.graph_weight, Unset):
            graph_weight = UNSET
        else:
            graph_weight = self.graph_weight

        limit = self.limit

        max_depth = self.max_depth

        max_seeds = self.max_seeds

        min_weight_fraction: Union[None, Unset, float]
        if isinstance(self.min_weight_fraction, Unset):
            min_weight_fraction = UNSET
        else:
            min_weight_fraction = self.min_weight_fraction

        rrf = self.rrf

        text_query: Union[None, Unset, str]
        if isinstance(self.text_query, Unset):
            text_query = UNSET
        else:
            text_query = self.text_query

        total_budget: Union[None, Unset, int]
        if isinstance(self.total_budget, Unset):
            total_budget = UNSET
        else:
            total_budget = self.total_budget

        vector_weight: Union[None, Unset, float]
        if isinstance(self.vector_weight, Unset):
            vector_weight = UNSET
        else:
            vector_weight = self.vector_weight

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "query_vector": query_vector,
                "vector_collection": vector_collection,
            }
        )
        if consensus_beta is not UNSET:
            field_dict["consensus_beta"] = consensus_beta
        if document_collection is not UNSET:
            field_dict["document_collection"] = document_collection
        if document_weight is not UNSET:
            field_dict["document_weight"] = document_weight
        if edge_types is not UNSET:
            field_dict["edge_types"] = edge_types
        if grain is not UNSET:
            field_dict["grain"] = grain
        if graph_weight is not UNSET:
            field_dict["graph_weight"] = graph_weight
        if limit is not UNSET:
            field_dict["limit"] = limit
        if max_depth is not UNSET:
            field_dict["max_depth"] = max_depth
        if max_seeds is not UNSET:
            field_dict["max_seeds"] = max_seeds
        if min_weight_fraction is not UNSET:
            field_dict["min_weight_fraction"] = min_weight_fraction
        if rrf is not UNSET:
            field_dict["rrf"] = rrf
        if text_query is not UNSET:
            field_dict["text_query"] = text_query
        if total_budget is not UNSET:
            field_dict["total_budget"] = total_budget
        if vector_weight is not UNSET:
            field_dict["vector_weight"] = vector_weight

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        query_vector = cast(list[float], d.pop("query_vector"))

        vector_collection = d.pop("vector_collection")

        def _parse_consensus_beta(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        consensus_beta = _parse_consensus_beta(d.pop("consensus_beta", UNSET))

        def _parse_document_collection(data: object) -> Union[None, Unset, str]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, str], data)

        document_collection = _parse_document_collection(
            d.pop("document_collection", UNSET)
        )

        def _parse_document_weight(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        document_weight = _parse_document_weight(d.pop("document_weight", UNSET))

        edge_types = cast(list[str], d.pop("edge_types", UNSET))

        def _parse_grain(data: object) -> Union[None, Unset, str]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, str], data)

        grain = _parse_grain(d.pop("grain", UNSET))

        def _parse_graph_weight(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        graph_weight = _parse_graph_weight(d.pop("graph_weight", UNSET))

        limit = d.pop("limit", UNSET)

        max_depth = d.pop("max_depth", UNSET)

        max_seeds = d.pop("max_seeds", UNSET)

        def _parse_min_weight_fraction(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        min_weight_fraction = _parse_min_weight_fraction(
            d.pop("min_weight_fraction", UNSET)
        )

        rrf = d.pop("rrf", UNSET)

        def _parse_text_query(data: object) -> Union[None, Unset, str]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, str], data)

        text_query = _parse_text_query(d.pop("text_query", UNSET))

        def _parse_total_budget(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        total_budget = _parse_total_budget(d.pop("total_budget", UNSET))

        def _parse_vector_weight(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        vector_weight = _parse_vector_weight(d.pop("vector_weight", UNSET))

        fusion_search_request = cls(
            query_vector=query_vector,
            vector_collection=vector_collection,
            consensus_beta=consensus_beta,
            document_collection=document_collection,
            document_weight=document_weight,
            edge_types=edge_types,
            grain=grain,
            graph_weight=graph_weight,
            limit=limit,
            max_depth=max_depth,
            max_seeds=max_seeds,
            min_weight_fraction=min_weight_fraction,
            rrf=rrf,
            text_query=text_query,
            total_budget=total_budget,
            vector_weight=vector_weight,
        )

        fusion_search_request.additional_properties = d
        return fusion_search_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
