# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="IvfConfigOutput")


@_attrs_define
class IvfConfigOutput:
    """REST output for IVF params (mirrors gRPC `V2IvfConfig`).

    Attributes:
        n_lists (int | None | Unset):
        n_probe (int | None | Unset):
    """

    n_lists: int | None | Unset = UNSET
    n_probe: int | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        n_lists: int | None | Unset
        if isinstance(self.n_lists, Unset):
            n_lists = UNSET
        else:
            n_lists = self.n_lists

        n_probe: int | None | Unset
        if isinstance(self.n_probe, Unset):
            n_probe = UNSET
        else:
            n_probe = self.n_probe

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if n_lists is not UNSET:
            field_dict["n_lists"] = n_lists
        if n_probe is not UNSET:
            field_dict["n_probe"] = n_probe

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)

        def _parse_n_lists(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        n_lists = _parse_n_lists(d.pop("n_lists", UNSET))

        def _parse_n_probe(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        n_probe = _parse_n_probe(d.pop("n_probe", UNSET))

        ivf_config_output = cls(
            n_lists=n_lists,
            n_probe=n_probe,
        )

        ivf_config_output.additional_properties = d
        return ivf_config_output

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
