# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.metric_aggregation_input_labels import MetricAggregationInputLabels


T = TypeVar("T", bound="MetricAggregationInput")


@_attrs_define
class MetricAggregationInput:
    """
    Attributes:
        metric_name (str):
        start_time_ns (int):
        end_time_ns (int):
        aggregation (str | Unset): Canonical: min, max, avg, sum, count. Percentile/rate forms also accepted: p50, p90,
            p95, p99, rate. Default: 'avg'.
        step_seconds (int | Unset):  Default: 60.
        group_by (list[str] | Unset):
        labels (MetricAggregationInputLabels | Unset):
    """

    metric_name: str
    start_time_ns: int
    end_time_ns: int
    aggregation: str | Unset = "avg"
    step_seconds: int | Unset = 60
    group_by: list[str] | Unset = UNSET
    labels: MetricAggregationInputLabels | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.metric_aggregation_input_labels import (
            MetricAggregationInputLabels,
        )

        metric_name = self.metric_name

        start_time_ns = self.start_time_ns

        end_time_ns = self.end_time_ns

        aggregation = self.aggregation

        step_seconds = self.step_seconds

        group_by: list[str] | Unset = UNSET
        if not isinstance(self.group_by, Unset):
            group_by = self.group_by

        labels: dict[str, Any] | Unset = UNSET
        if not isinstance(self.labels, Unset):
            labels = self.labels.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "metric_name": metric_name,
                "start_time_ns": start_time_ns,
                "end_time_ns": end_time_ns,
            }
        )
        if aggregation is not UNSET:
            field_dict["aggregation"] = aggregation
        if step_seconds is not UNSET:
            field_dict["step_seconds"] = step_seconds
        if group_by is not UNSET:
            field_dict["group_by"] = group_by
        if labels is not UNSET:
            field_dict["labels"] = labels

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.metric_aggregation_input_labels import (
            MetricAggregationInputLabels,
        )

        d = dict(src_dict)
        metric_name = d.pop("metric_name")

        start_time_ns = d.pop("start_time_ns")

        end_time_ns = d.pop("end_time_ns")

        aggregation = d.pop("aggregation", UNSET)

        step_seconds = d.pop("step_seconds", UNSET)

        group_by = cast(list[str], d.pop("group_by", UNSET))

        _labels = d.pop("labels", UNSET)
        labels: MetricAggregationInputLabels | Unset
        if isinstance(_labels, Unset):
            labels = UNSET
        else:
            labels = MetricAggregationInputLabels.from_dict(_labels)

        metric_aggregation_input = cls(
            metric_name=metric_name,
            start_time_ns=start_time_ns,
            end_time_ns=end_time_ns,
            aggregation=aggregation,
            step_seconds=step_seconds,
            group_by=group_by,
            labels=labels,
        )

        metric_aggregation_input.additional_properties = d
        return metric_aggregation_input

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
