# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.proxima_record_input_props_type_0 import ProximaRecordInputPropsType0
    from ..models.text_field_input import TextFieldInput


T = TypeVar("T", bound="ProximaRecordInput")


@_attrs_define
class ProximaRecordInput:
    """Input format for ProximaRecord (JSON-friendly)

    This is the JSON-serializable input format for ProximaRecord.
    It uses serde_json::Value for typed fields to support dynamic typing
    at the API boundary, with validation happening during conversion.

        Attributes:
            vector (list[float]): Vector embedding (required)
            id (Union[None, Unset, str]): Record ID (optional, will be auto-generated if not provided)
            props (Union['ProximaRecordInputPropsType0', None, Unset]): Canonical rich property map.
            text_fields (Union[None, Unset, list['TextFieldInput']]): Dedicated TEXT fields with storage hints
    """

    vector: list[float]
    id: Union[None, Unset, str] = UNSET
    props: Union["ProximaRecordInputPropsType0", None, Unset] = UNSET
    text_fields: Union[None, Unset, list["TextFieldInput"]] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.proxima_record_input_props_type_0 import (
            ProximaRecordInputPropsType0,
        )
        from ..models.text_field_input import TextFieldInput

        vector = self.vector

        id: Union[None, Unset, str]
        if isinstance(self.id, Unset):
            id = UNSET
        else:
            id = self.id

        props: Union[None, Unset, dict[str, Any]]
        if isinstance(self.props, Unset):
            props = UNSET
        elif isinstance(self.props, ProximaRecordInputPropsType0):
            props = self.props.to_dict()
        else:
            props = self.props

        text_fields: Union[None, Unset, list[dict[str, Any]]]
        if isinstance(self.text_fields, Unset):
            text_fields = UNSET
        elif isinstance(self.text_fields, list):
            text_fields = []
            for text_fields_type_0_item_data in self.text_fields:
                text_fields_type_0_item = text_fields_type_0_item_data.to_dict()
                text_fields.append(text_fields_type_0_item)

        else:
            text_fields = self.text_fields

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "vector": vector,
            }
        )
        if id is not UNSET:
            field_dict["id"] = id
        if props is not UNSET:
            field_dict["props"] = props
        if text_fields is not UNSET:
            field_dict["text_fields"] = text_fields

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.proxima_record_input_props_type_0 import (
            ProximaRecordInputPropsType0,
        )
        from ..models.text_field_input import TextFieldInput

        d = dict(src_dict)
        vector = cast(list[float], d.pop("vector"))

        def _parse_id(data: object) -> Union[None, Unset, str]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, str], data)

        id = _parse_id(d.pop("id", UNSET))

        def _parse_props(
            data: object,
        ) -> Union["ProximaRecordInputPropsType0", None, Unset]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                props_type_0 = ProximaRecordInputPropsType0.from_dict(data)

                return props_type_0
            except:  # noqa: E722
                pass
            return cast(Union["ProximaRecordInputPropsType0", None, Unset], data)

        props = _parse_props(d.pop("props", UNSET))

        def _parse_text_fields(
            data: object,
        ) -> Union[None, Unset, list["TextFieldInput"]]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                text_fields_type_0 = []
                _text_fields_type_0 = data
                for text_fields_type_0_item_data in _text_fields_type_0:
                    text_fields_type_0_item = TextFieldInput.from_dict(
                        text_fields_type_0_item_data
                    )

                    text_fields_type_0.append(text_fields_type_0_item)

                return text_fields_type_0
            except:  # noqa: E722
                pass
            return cast(Union[None, Unset, list["TextFieldInput"]], data)

        text_fields = _parse_text_fields(d.pop("text_fields", UNSET))

        proxima_record_input = cls(
            vector=vector,
            id=id,
            props=props,
            text_fields=text_fields,
        )

        proxima_record_input.additional_properties = d
        return proxima_record_input

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
