# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.resolved_embedding_model_response import (
        ResolvedEmbeddingModelResponse,
    )


T = TypeVar("T", bound="ResolvedModelBindingResponse")


@_attrs_define
class ResolvedModelBindingResponse:
    """
    Attributes:
        model (str):
        dimension (int):
        model_asset_id (str):
        model_version (int):
        contract_sha256 (str):
        snapshot (ResolvedEmbeddingModelResponse):
    """

    model: str
    dimension: int
    model_asset_id: str
    model_version: int
    contract_sha256: str
    snapshot: ResolvedEmbeddingModelResponse
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.resolved_embedding_model_response import (
            ResolvedEmbeddingModelResponse,
        )

        model = self.model

        dimension = self.dimension

        model_asset_id = self.model_asset_id

        model_version = self.model_version

        contract_sha256 = self.contract_sha256

        snapshot = self.snapshot.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "model": model,
                "dimension": dimension,
                "model_asset_id": model_asset_id,
                "model_version": model_version,
                "contract_sha256": contract_sha256,
                "snapshot": snapshot,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.resolved_embedding_model_response import (
            ResolvedEmbeddingModelResponse,
        )

        d = dict(src_dict)
        model = d.pop("model")

        dimension = d.pop("dimension")

        model_asset_id = d.pop("model_asset_id")

        model_version = d.pop("model_version")

        contract_sha256 = d.pop("contract_sha256")

        snapshot = ResolvedEmbeddingModelResponse.from_dict(d.pop("snapshot"))

        resolved_model_binding_response = cls(
            model=model,
            dimension=dimension,
            model_asset_id=model_asset_id,
            model_version=model_version,
            contract_sha256=contract_sha256,
            snapshot=snapshot,
        )

        resolved_model_binding_response.additional_properties = d
        return resolved_model_binding_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
