# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="RestColumnDefinition")


@_attrs_define
class RestColumnDefinition:
    """Column definition for schema

    Attributes:
        data_type (str): Data type

            Supported types:
            - "text": Variable-length UTF-8 text
            - "text_large": Large text with sidecar storage
            - "integer": 64-bit signed integer
            - "float": 64-bit floating point
            - "decimal": 128-bit decimal (precision, scale)
            - "boolean": True/false
            - "timestamp": Microseconds since epoch
            - "timestamp_tz": Timestamp with timezone
            - "date": Days since epoch
            - "time": Microseconds since midnight
            - "uuid": RFC 4122 UUID
            - "binary": Raw bytes
            - "json": Validated JSON
            - "array_text", "array_integer", "array_float", "array_boolean"
            - "map_string_string", "map_string_any"
            - "geo_point": Latitude/longitude point
            - "vector": Fixed-dimension vector (specify dimension)
        name (str): Column name
        filterable (Union[None, Unset, bool]): Enable filtering on this column

            When true, the column can be used in WHERE clauses.
            Default: true for indexed columns, false otherwise
        indexed (Union[None, Unset, bool]): Create secondary index for this column

            Improves query performance for equality/range filters.
            Default: false
        max_length (Union[None, Unset, int]): Maximum length for TEXT/BINARY columns

            Default: no limit
        nullable (Union[None, Unset, bool]): Whether null values are allowed

            Default: true
        precision (Union[None, Unset, int]): Precision for DECIMAL type (1-38)
        scale (Union[None, Unset, int]): Scale for DECIMAL type (0-precision)
        vector_dimension (Union[None, Unset, int]): Dimension for VECTOR type
    """

    data_type: str
    name: str
    filterable: Union[None, Unset, bool] = UNSET
    indexed: Union[None, Unset, bool] = UNSET
    max_length: Union[None, Unset, int] = UNSET
    nullable: Union[None, Unset, bool] = UNSET
    precision: Union[None, Unset, int] = UNSET
    scale: Union[None, Unset, int] = UNSET
    vector_dimension: Union[None, Unset, int] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        data_type = self.data_type

        name = self.name

        filterable: Union[None, Unset, bool]
        if isinstance(self.filterable, Unset):
            filterable = UNSET
        else:
            filterable = self.filterable

        indexed: Union[None, Unset, bool]
        if isinstance(self.indexed, Unset):
            indexed = UNSET
        else:
            indexed = self.indexed

        max_length: Union[None, Unset, int]
        if isinstance(self.max_length, Unset):
            max_length = UNSET
        else:
            max_length = self.max_length

        nullable: Union[None, Unset, bool]
        if isinstance(self.nullable, Unset):
            nullable = UNSET
        else:
            nullable = self.nullable

        precision: Union[None, Unset, int]
        if isinstance(self.precision, Unset):
            precision = UNSET
        else:
            precision = self.precision

        scale: Union[None, Unset, int]
        if isinstance(self.scale, Unset):
            scale = UNSET
        else:
            scale = self.scale

        vector_dimension: Union[None, Unset, int]
        if isinstance(self.vector_dimension, Unset):
            vector_dimension = UNSET
        else:
            vector_dimension = self.vector_dimension

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "data_type": data_type,
                "name": name,
            }
        )
        if filterable is not UNSET:
            field_dict["filterable"] = filterable
        if indexed is not UNSET:
            field_dict["indexed"] = indexed
        if max_length is not UNSET:
            field_dict["max_length"] = max_length
        if nullable is not UNSET:
            field_dict["nullable"] = nullable
        if precision is not UNSET:
            field_dict["precision"] = precision
        if scale is not UNSET:
            field_dict["scale"] = scale
        if vector_dimension is not UNSET:
            field_dict["vector_dimension"] = vector_dimension

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        data_type = d.pop("data_type")

        name = d.pop("name")

        def _parse_filterable(data: object) -> Union[None, Unset, bool]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, bool], data)

        filterable = _parse_filterable(d.pop("filterable", UNSET))

        def _parse_indexed(data: object) -> Union[None, Unset, bool]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, bool], data)

        indexed = _parse_indexed(d.pop("indexed", UNSET))

        def _parse_max_length(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        max_length = _parse_max_length(d.pop("max_length", UNSET))

        def _parse_nullable(data: object) -> Union[None, Unset, bool]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, bool], data)

        nullable = _parse_nullable(d.pop("nullable", UNSET))

        def _parse_precision(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        precision = _parse_precision(d.pop("precision", UNSET))

        def _parse_scale(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        scale = _parse_scale(d.pop("scale", UNSET))

        def _parse_vector_dimension(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        vector_dimension = _parse_vector_dimension(d.pop("vector_dimension", UNSET))

        rest_column_definition = cls(
            data_type=data_type,
            name=name,
            filterable=filterable,
            indexed=indexed,
            max_length=max_length,
            nullable=nullable,
            precision=precision,
            scale=scale,
            vector_dimension=vector_dimension,
        )

        rest_column_definition.additional_properties = d
        return rest_column_definition

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
