# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ScanRecordsRequest")


@_attrs_define
class ScanRecordsRequest:
    """Body of `POST /records/scan`. Mirrors the OpenAPI `ScanRecordsRequest`
    schema; all fields optional so an empty `{}` returns the first page.

        Attributes:
            cursor (Union[None, Unset, str]): Opaque continuation token returned as `next_cursor` from a
                prior page. Omit / null to start from the beginning.
            filter_ (Union[Unset, Any]): Metadata filter applied (before the limit) to the scanned page.
                Accepts either the typed list form `[{field,op,value}]` (mirrors
                `searchRecords.filters`) or a simple equality map `{field: value}`.
            include_text (Union[None, Unset, bool]):
            include_vector (Union[None, Unset, bool]):
            limit (Union[None, Unset, int]): Max records to return in this page. Server enforces upper bound.
    """

    cursor: Union[None, Unset, str] = UNSET
    filter_: Union[Unset, Any] = UNSET
    include_text: Union[None, Unset, bool] = UNSET
    include_vector: Union[None, Unset, bool] = UNSET
    limit: Union[None, Unset, int] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        cursor: Union[None, Unset, str]
        if isinstance(self.cursor, Unset):
            cursor = UNSET
        else:
            cursor = self.cursor

        filter_ = self.filter_

        include_text: Union[None, Unset, bool]
        if isinstance(self.include_text, Unset):
            include_text = UNSET
        else:
            include_text = self.include_text

        include_vector: Union[None, Unset, bool]
        if isinstance(self.include_vector, Unset):
            include_vector = UNSET
        else:
            include_vector = self.include_vector

        limit: Union[None, Unset, int]
        if isinstance(self.limit, Unset):
            limit = UNSET
        else:
            limit = self.limit

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if cursor is not UNSET:
            field_dict["cursor"] = cursor
        if filter_ is not UNSET:
            field_dict["filter"] = filter_
        if include_text is not UNSET:
            field_dict["include_text"] = include_text
        if include_vector is not UNSET:
            field_dict["include_vector"] = include_vector
        if limit is not UNSET:
            field_dict["limit"] = limit

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)

        def _parse_cursor(data: object) -> Union[None, Unset, str]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, str], data)

        cursor = _parse_cursor(d.pop("cursor", UNSET))

        filter_ = d.pop("filter", UNSET)

        def _parse_include_text(data: object) -> Union[None, Unset, bool]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, bool], data)

        include_text = _parse_include_text(d.pop("include_text", UNSET))

        def _parse_include_vector(data: object) -> Union[None, Unset, bool]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, bool], data)

        include_vector = _parse_include_vector(d.pop("include_vector", UNSET))

        def _parse_limit(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        limit = _parse_limit(d.pop("limit", UNSET))

        scan_records_request = cls(
            cursor=cursor,
            filter_=filter_,
            include_text=include_text,
            include_vector=include_vector,
            limit=limit,
        )

        scan_records_request.additional_properties = d
        return scan_records_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
