# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.search_entities_request_filters import SearchEntitiesRequestFilters


T = TypeVar("T", bound="SearchEntitiesRequest")


@_attrs_define
class SearchEntitiesRequest:
    """
    Attributes:
        filters (Union[Unset, SearchEntitiesRequestFilters]): Equality metadata filters as a `{field: value}` JSON
            object.
        query_vector (Union[Unset, list[float]]): Query embedding for vector similarity search. Omit for metadata-only
            search.
        top_k (Union[Unset, int]):
    """

    filters: Union[Unset, "SearchEntitiesRequestFilters"] = UNSET
    query_vector: Union[Unset, list[float]] = UNSET
    top_k: Union[Unset, int] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.search_entities_request_filters import (
            SearchEntitiesRequestFilters,
        )

        filters: Union[Unset, dict[str, Any]] = UNSET
        if not isinstance(self.filters, Unset):
            filters = self.filters.to_dict()

        query_vector: Union[Unset, list[float]] = UNSET
        if not isinstance(self.query_vector, Unset):
            query_vector = self.query_vector

        top_k = self.top_k

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if filters is not UNSET:
            field_dict["filters"] = filters
        if query_vector is not UNSET:
            field_dict["query_vector"] = query_vector
        if top_k is not UNSET:
            field_dict["top_k"] = top_k

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.search_entities_request_filters import (
            SearchEntitiesRequestFilters,
        )

        d = dict(src_dict)
        _filters = d.pop("filters", UNSET)
        filters: Union[Unset, SearchEntitiesRequestFilters]
        if isinstance(_filters, Unset):
            filters = UNSET
        else:
            filters = SearchEntitiesRequestFilters.from_dict(_filters)

        query_vector = cast(list[float], d.pop("query_vector", UNSET))

        top_k = d.pop("top_k", UNSET)

        search_entities_request = cls(
            filters=filters,
            query_vector=query_vector,
            top_k=top_k,
        )

        search_entities_request.additional_properties = d
        return search_entities_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
