# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="TextFieldOutput")


@_attrs_define
class TextFieldOutput:
    """Output format for TEXT fields

    Attributes:
        content (str): Text content (may be truncated for large content)
        name (str): Field name
        truncated (bool): Whether content was truncated
        chunk_count (Union[None, Unset, int]): Number of chunks (for chunked storage)
    """

    content: str
    name: str
    truncated: bool
    chunk_count: Union[None, Unset, int] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        content = self.content

        name = self.name

        truncated = self.truncated

        chunk_count: Union[None, Unset, int]
        if isinstance(self.chunk_count, Unset):
            chunk_count = UNSET
        else:
            chunk_count = self.chunk_count

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "content": content,
                "name": name,
                "truncated": truncated,
            }
        )
        if chunk_count is not UNSET:
            field_dict["chunk_count"] = chunk_count

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        content = d.pop("content")

        name = d.pop("name")

        truncated = d.pop("truncated")

        def _parse_chunk_count(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        chunk_count = _parse_chunk_count(d.pop("chunk_count", UNSET))

        text_field_output = cls(
            content=content,
            name=name,
            truncated=truncated,
            chunk_count=chunk_count,
        )

        text_field_output.additional_properties = d
        return text_field_output

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
