# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.ts_point_tags import TsPointTags
    from ..models.ts_point_values import TsPointValues


T = TypeVar("T", bound="TsPoint")


@_attrs_define
class TsPoint:
    """
    Attributes:
        timestamp (int): Epoch milliseconds.
        values (TsPointValues | Unset):
        tags (TsPointTags | Unset):
    """

    timestamp: int
    values: TsPointValues | Unset = UNSET
    tags: TsPointTags | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.ts_point_tags import TsPointTags
        from ..models.ts_point_values import TsPointValues

        timestamp = self.timestamp

        values: dict[str, Any] | Unset = UNSET
        if not isinstance(self.values, Unset):
            values = self.values.to_dict()

        tags: dict[str, Any] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "timestamp": timestamp,
            }
        )
        if values is not UNSET:
            field_dict["values"] = values
        if tags is not UNSET:
            field_dict["tags"] = tags

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.ts_point_tags import TsPointTags
        from ..models.ts_point_values import TsPointValues

        d = dict(src_dict)
        timestamp = d.pop("timestamp")

        _values = d.pop("values", UNSET)
        values: TsPointValues | Unset
        if isinstance(_values, Unset):
            values = UNSET
        else:
            values = TsPointValues.from_dict(_values)

        _tags = d.pop("tags", UNSET)
        tags: TsPointTags | Unset
        if isinstance(_tags, Unset):
            tags = UNSET
        else:
            tags = TsPointTags.from_dict(_tags)

        ts_point = cls(
            timestamp=timestamp,
            values=values,
            tags=tags,
        )

        ts_point.additional_properties = d
        return ts_point

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
