# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Optional, TextIO, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.typed_search_result import TypedSearchResult


T = TypeVar("T", bound="TypedSearchResponse")


@_attrs_define
class TypedSearchResponse:
    """Search response with typed results

    Attributes:
        latency_ms (int): Search latency in milliseconds
        request_id (str): Request ID for tracing
        results (list['TypedSearchResult']): Search results
        explain (Union[Unset, Any]): Human-readable explain summary derived from the SearchPlanTrace.
            Only emitted when the request sets `debug=true` — gives an on-call
            operator a one-glance view of the plan, cache result, and any
            actionable hints (high scan fraction, repair triggered, ...).
        search_plan_trace (Union[Unset, Any]): SearchPlanTrace (LLD §10) — the per-query telemetry envelope that
            upstream gateways consume for metering and planner-v2 training.
            Phase 0 emits a stub trace populated from request_id + latency; later
            phases fill in the per-stage counters. Only emitted when the request
            sets `debug=true` (LLD §1 contract).
        total_matches (Union[None, Unset, int]): Total number of matching documents (before top_k limit)
    """

    latency_ms: int
    request_id: str
    results: list["TypedSearchResult"]
    explain: Union[Unset, Any] = UNSET
    search_plan_trace: Union[Unset, Any] = UNSET
    total_matches: Union[None, Unset, int] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.typed_search_result import TypedSearchResult

        latency_ms = self.latency_ms

        request_id = self.request_id

        results = []
        for results_item_data in self.results:
            results_item = results_item_data.to_dict()
            results.append(results_item)

        explain = self.explain

        search_plan_trace = self.search_plan_trace

        total_matches: Union[None, Unset, int]
        if isinstance(self.total_matches, Unset):
            total_matches = UNSET
        else:
            total_matches = self.total_matches

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "latency_ms": latency_ms,
                "request_id": request_id,
                "results": results,
            }
        )
        if explain is not UNSET:
            field_dict["explain"] = explain
        if search_plan_trace is not UNSET:
            field_dict["search_plan_trace"] = search_plan_trace
        if total_matches is not UNSET:
            field_dict["total_matches"] = total_matches

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.typed_search_result import TypedSearchResult

        d = dict(src_dict)
        latency_ms = d.pop("latency_ms")

        request_id = d.pop("request_id")

        results = []
        _results = d.pop("results")
        for results_item_data in _results:
            results_item = TypedSearchResult.from_dict(results_item_data)

            results.append(results_item)

        explain = d.pop("explain", UNSET)

        search_plan_trace = d.pop("search_plan_trace", UNSET)

        def _parse_total_matches(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        total_matches = _parse_total_matches(d.pop("total_matches", UNSET))

        typed_search_response = cls(
            latency_ms=latency_ms,
            request_id=request_id,
            results=results,
            explain=explain,
            search_plan_trace=search_plan_trace,
            total_matches=total_matches,
        )

        typed_search_response.additional_properties = d
        return typed_search_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
