# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, BinaryIO, Generator, TextIO, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="WalkStepRequest")


@_attrs_define
class WalkStepRequest:
    """
    Attributes:
        node_id (str):
        edge_type (str | Unset):
        limit (int | Unset): Accepted but currently unused server-side. Default: 50.
    """

    node_id: str
    edge_type: str | Unset = UNSET
    limit: int | Unset = 50
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        node_id = self.node_id

        edge_type = self.edge_type

        limit = self.limit

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "node_id": node_id,
            }
        )
        if edge_type is not UNSET:
            field_dict["edge_type"] = edge_type
        if limit is not UNSET:
            field_dict["limit"] = limit

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        node_id = d.pop("node_id")

        edge_type = d.pop("edge_type", UNSET)

        limit = d.pop("limit", UNSET)

        walk_step_request = cls(
            node_id=node_id,
            edge_type=edge_type,
            limit=limit,
        )

        walk_step_request.additional_properties = d
        return walk_step_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
