# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.sql_request import SqlRequest
from ...models.sql_response import SqlResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: SqlRequest,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/sql",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ErrorResponse | SqlResponse | None:
    if response.status_code == 200:
        response_200 = SqlResponse.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = ErrorResponse.from_dict(response.json())

        return response_400

    if response.status_code == 408:
        response_408 = ErrorResponse.from_dict(response.json())

        return response_408

    if response.status_code == 409:
        response_409 = ErrorResponse.from_dict(response.json())

        return response_409

    if response.status_code == 500:
        response_500 = ErrorResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ErrorResponse | SqlResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: SqlRequest,
    x_tenant_id: str | Unset = UNSET,
) -> Response[ErrorResponse | SqlResponse]:
    """Execute one authenticated SQL statement.

     The required foundation identity is inserted by the root tenant middleware
    after authentication. A router mounted without that middleware fails closed
    at extraction instead of constructing an anonymous authorization carrier.

    Args:
        x_tenant_id (str | Unset):
        body (SqlRequest): One SQL statement executed through the shared SQL authority.

            Parameter binding is intentionally not advertised yet: the relational
            execution port currently has no typed binding contract. Callers must not be
            offered a field that an adapter would silently ignore or interpolate.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | SqlResponse]
    """

    kwargs = _get_kwargs(
        body=body,
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: SqlRequest,
    x_tenant_id: str | Unset = UNSET,
) -> ErrorResponse | SqlResponse | None:
    """Execute one authenticated SQL statement.

     The required foundation identity is inserted by the root tenant middleware
    after authentication. A router mounted without that middleware fails closed
    at extraction instead of constructing an anonymous authorization carrier.

    Args:
        x_tenant_id (str | Unset):
        body (SqlRequest): One SQL statement executed through the shared SQL authority.

            Parameter binding is intentionally not advertised yet: the relational
            execution port currently has no typed binding contract. Callers must not be
            offered a field that an adapter would silently ignore or interpolate.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | SqlResponse
    """

    return sync_detailed(
        client=client,
        body=body,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: SqlRequest,
    x_tenant_id: str | Unset = UNSET,
) -> Response[ErrorResponse | SqlResponse]:
    """Execute one authenticated SQL statement.

     The required foundation identity is inserted by the root tenant middleware
    after authentication. A router mounted without that middleware fails closed
    at extraction instead of constructing an anonymous authorization carrier.

    Args:
        x_tenant_id (str | Unset):
        body (SqlRequest): One SQL statement executed through the shared SQL authority.

            Parameter binding is intentionally not advertised yet: the relational
            execution port currently has no typed binding contract. Callers must not be
            offered a field that an adapter would silently ignore or interpolate.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | SqlResponse]
    """

    kwargs = _get_kwargs(
        body=body,
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: SqlRequest,
    x_tenant_id: str | Unset = UNSET,
) -> ErrorResponse | SqlResponse | None:
    """Execute one authenticated SQL statement.

     The required foundation identity is inserted by the root tenant middleware
    after authentication. A router mounted without that middleware fails closed
    at extraction instead of constructing an anonymous authorization carrier.

    Args:
        x_tenant_id (str | Unset):
        body (SqlRequest): One SQL statement executed through the shared SQL authority.

            Parameter binding is intentionally not advertised yet: the relational
            execution port currently has no typed binding contract. Callers must not be
            offered a field that an adapter would silently ignore or interpolate.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | SqlResponse
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
