# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.ts_delete_response import TsDeleteResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    collection_id: str,
    *,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/api/v2/timeseries/collections/{collection_id}".format(
            collection_id=quote(str(collection_id), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ErrorResponse | TsDeleteResponse | None:
    if response.status_code == 200:
        response_200 = TsDeleteResponse.from_dict(response.json())

        return response_200

    if response.status_code == 500:
        response_500 = ErrorResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ErrorResponse | TsDeleteResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[ErrorResponse | TsDeleteResponse]:
    """Delete a time-series collection.

     Always 200; `success` distinguishes an actual deletion from a
    no-op (unknown collection).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | TsDeleteResponse]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> ErrorResponse | TsDeleteResponse | None:
    """Delete a time-series collection.

     Always 200; `success` distinguishes an actual deletion from a
    no-op (unknown collection).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | TsDeleteResponse
    """

    return sync_detailed(
        collection_id=collection_id,
        client=client,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[ErrorResponse | TsDeleteResponse]:
    """Delete a time-series collection.

     Always 200; `success` distinguishes an actual deletion from a
    no-op (unknown collection).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | TsDeleteResponse]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    collection_id: str,
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> ErrorResponse | TsDeleteResponse | None:
    """Delete a time-series collection.

     Always 200; `success` distinguishes an actual deletion from a
    no-op (unknown collection).

    Args:
        collection_id (str):
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | TsDeleteResponse
    """

    return (
        await asyncio_detailed(
            collection_id=collection_id,
            client=client,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
