// This file is @generated by prost-build.
/// # =============================================================================
/// TypedValue: Strongly-typed value wrapper
///
/// Used in typed_fields map for schema-validated columns.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypedValue {
    #[prost(enumeration = "ColumnDataType", tag = "1")]
    pub declared_type: i32,
    #[prost(
        oneof = "typed_value::Value",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 30, 31, 32, 33, 34, 40, 41, 42, 50, 51, 52, 53, 99"
    )]
    pub value: ::core::option::Option<typed_value::Value>,
}
/// Nested message and enum types in `TypedValue`.
pub mod typed_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        /// Text
        #[prost(string, tag = "10")]
        TextValue(::prost::alloc::string::String),
        /// Numeric
        #[prost(int64, tag = "11")]
        IntegerValue(i64),
        #[prost(double, tag = "12")]
        FloatValue(f64),
        #[prost(message, tag = "13")]
        DecimalValue(super::DecimalValue),
        /// Boolean
        #[prost(bool, tag = "14")]
        BooleanValue(bool),
        /// Temporal
        ///
        /// Microseconds since epoch
        #[prost(int64, tag = "15")]
        TimestampValue(i64),
        #[prost(message, tag = "16")]
        TimestampTzValue(super::TimestampTzValue),
        /// Days since epoch
        #[prost(int32, tag = "17")]
        DateValue(i32),
        /// Microseconds since midnight
        #[prost(int64, tag = "18")]
        TimeValue(i64),
        /// Duration in microseconds
        #[prost(int64, tag = "19")]
        DurationValue(i64),
        #[prost(message, tag = "20")]
        IntervalValue(super::IntervalValue),
        /// Identifier
        ///
        /// 16-byte UUID
        #[prost(bytes, tag = "21")]
        UuidValue(::prost::alloc::vec::Vec<u8>),
        /// Binary
        #[prost(bytes, tag = "22")]
        BinaryValue(::prost::alloc::vec::Vec<u8>),
        /// Structured
        ///
        /// JSON string (validated)
        #[prost(string, tag = "23")]
        JsonValue(::prost::alloc::string::String),
        /// Arrays
        #[prost(message, tag = "30")]
        TextArray(super::TextArray),
        #[prost(message, tag = "31")]
        IntegerArray(super::IntegerArray),
        #[prost(message, tag = "32")]
        FloatArray(super::FloatArray),
        #[prost(message, tag = "33")]
        BooleanArray(super::BooleanArray),
        #[prost(message, tag = "34")]
        UuidArray(super::UuidArray),
        /// Maps
        #[prost(message, tag = "40")]
        StringStringMap(super::StringStringMap),
        #[prost(message, tag = "41")]
        StringIntegerMap(super::StringIntegerMap),
        #[prost(message, tag = "42")]
        StringFloatMap(super::StringFloatMap),
        /// Geospatial
        #[prost(message, tag = "50")]
        GeoPoint(super::GeoPoint),
        #[prost(message, tag = "51")]
        GeoPolygon(super::GeoPolygon),
        /// Vector
        #[prost(message, tag = "52")]
        VectorValue(super::FloatArray),
        #[prost(message, tag = "53")]
        SparseVectorValue(super::SparseVector),
        /// Null marker
        #[prost(bool, tag = "99")]
        IsNull(bool),
    }
}
/// Decimal with precision and scale
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecimalValue {
    /// i128 as 16 bytes, little-endian
    #[prost(bytes = "vec", tag = "1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// Total digits (max 38)
    #[prost(uint32, tag = "2")]
    pub precision: u32,
    /// Digits after decimal point
    #[prost(uint32, tag = "3")]
    pub scale: u32,
}
/// Timestamp with timezone
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimestampTzValue {
    /// Microseconds since epoch in UTC
    #[prost(int64, tag = "1")]
    pub timestamp_us: i64,
    /// IANA timezone (e.g., "America/New_York")
    #[prost(string, tag = "2")]
    pub timezone: ::prost::alloc::string::String,
}
/// Calendar interval
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntervalValue {
    #[prost(int32, tag = "1")]
    pub months: i32,
    #[prost(int32, tag = "2")]
    pub days: i32,
    #[prost(int64, tag = "3")]
    pub nanos: i64,
}
/// Array types
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextArray {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntegerArray {
    #[prost(int64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FloatArray {
    #[prost(double, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BooleanArray {
    #[prost(bool, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UuidArray {
    /// Each 16 bytes
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Map types
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringStringMap {
    #[prost(map = "string, string", tag = "1")]
    pub entries: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringIntegerMap {
    #[prost(map = "string, int64", tag = "1")]
    pub entries: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringFloatMap {
    #[prost(map = "string, double", tag = "1")]
    pub entries: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
}
/// Geospatial types
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GeoPoint {
    /// -90 to 90
    #[prost(double, tag = "1")]
    pub latitude: f64,
    /// -180 to 180
    #[prost(double, tag = "2")]
    pub longitude: f64,
    #[prost(double, optional, tag = "3")]
    pub altitude: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GeoPolygon {
    /// Ring of points, first == last
    #[prost(message, repeated, tag = "1")]
    pub points: ::prost::alloc::vec::Vec<GeoPoint>,
}
/// Sparse vector with indices
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SparseVector {
    #[prost(uint32, repeated, tag = "1")]
    pub indices: ::prost::alloc::vec::Vec<u32>,
    #[prost(float, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<f32>,
    /// Total dimension of sparse space
    #[prost(uint32, tag = "3")]
    pub dimension: u32,
}
/// # =============================================================================
/// TypedColumn: Column definition with validation constraints
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypedColumn {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ColumnDataType", tag = "2")]
    pub data_type: i32,
    /// Column properties
    ///
    /// Default: true
    #[prost(bool, tag = "3")]
    pub nullable: bool,
    /// Create secondary index for fast lookups
    #[prost(bool, tag = "4")]
    pub indexed: bool,
    /// Allow in WHERE clauses (enables statistics)
    #[prost(bool, tag = "5")]
    pub filterable: bool,
    /// Enforce uniqueness constraint
    #[prost(bool, tag = "6")]
    pub unique: bool,
    /// Validation constraints
    ///
    /// For TEXT/BINARY
    #[prost(uint32, optional, tag = "10")]
    pub max_length: ::core::option::Option<u32>,
    /// For TEXT/BINARY
    #[prost(uint32, optional, tag = "11")]
    pub min_length: ::core::option::Option<u32>,
    /// For INTEGER
    #[prost(int64, optional, tag = "12")]
    pub min_value: ::core::option::Option<i64>,
    /// For INTEGER
    #[prost(int64, optional, tag = "13")]
    pub max_value: ::core::option::Option<i64>,
    /// For FLOAT
    #[prost(double, optional, tag = "14")]
    pub min_float_value: ::core::option::Option<f64>,
    /// For FLOAT
    #[prost(double, optional, tag = "15")]
    pub max_float_value: ::core::option::Option<f64>,
    /// For TEXT validation
    #[prost(string, optional, tag = "16")]
    pub regex_pattern: ::core::option::Option<::prost::alloc::string::String>,
    /// Default value (serialized)
    #[prost(string, optional, tag = "17")]
    pub default_value: ::core::option::Option<::prost::alloc::string::String>,
    /// For DECIMAL (1-38)
    #[prost(uint32, optional, tag = "18")]
    pub decimal_precision: ::core::option::Option<u32>,
    /// For DECIMAL (0-precision)
    #[prost(uint32, optional, tag = "19")]
    pub decimal_scale: ::core::option::Option<u32>,
    /// For ARRAY types
    #[prost(uint32, optional, tag = "20")]
    pub array_max_items: ::core::option::Option<u32>,
    /// For JSON (default: 32)
    #[prost(uint32, optional, tag = "21")]
    pub json_max_depth: ::core::option::Option<u32>,
    /// JSON Schema for validation
    #[prost(string, optional, tag = "22")]
    pub json_schema: ::core::option::Option<::prost::alloc::string::String>,
    /// For TIMESTAMP_TZ default
    #[prost(string, optional, tag = "23")]
    pub timezone: ::core::option::Option<::prost::alloc::string::String>,
    /// TEXT-specific options
    #[prost(enumeration = "TextStorageStrategy", optional, tag = "30")]
    pub text_storage_strategy: ::core::option::Option<i32>,
    /// Create fulltext index
    #[prost(bool, optional, tag = "31")]
    pub enable_fulltext_index: ::core::option::Option<bool>,
    /// Create n-gram bloom filter
    #[prost(bool, optional, tag = "32")]
    pub enable_ngram_bloom: ::core::option::Option<bool>,
    /// N-gram size (default: 3)
    #[prost(uint32, optional, tag = "33")]
    pub ngram_size: ::core::option::Option<u32>,
    /// Description and metadata
    #[prost(string, optional, tag = "50")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "51")]
    pub annotations: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// # =============================================================================
/// RecordSchema: Schema definition with enforcement mode
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordSchema {
    /// UUID for this schema version
    #[prost(string, tag = "1")]
    pub schema_id: ::prost::alloc::string::String,
    /// Semantic version (e.g., "1.0.0")
    #[prost(string, tag = "2")]
    pub schema_version: ::prost::alloc::string::String,
    /// Human-readable name
    #[prost(string, tag = "3")]
    pub schema_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub columns: ::prost::alloc::vec::Vec<TypedColumn>,
    #[prost(enumeration = "SchemaEnforcementMode", tag = "5")]
    pub enforcement_mode: i32,
    /// For HYBRID mode
    #[prost(bool, tag = "6")]
    pub allow_additional_fields: bool,
    /// Schema evolution
    ///
    /// Previous version
    #[prost(string, optional, tag = "10")]
    pub parent_schema_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "11")]
    pub evolution_rules: ::prost::alloc::vec::Vec<SchemaEvolutionRule>,
    /// Metadata
    #[prost(int64, tag = "20")]
    pub created_at: i64,
    #[prost(string, optional, tag = "21")]
    pub created_by: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "22")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "23")]
    pub annotations: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Schema evolution rules for backward/forward compatibility
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SchemaEvolutionRule {
    #[prost(string, tag = "1")]
    pub rule_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SchemaEvolutionType", tag = "2")]
    pub rule_type: i32,
    #[prost(string, tag = "3")]
    pub source_column: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub target_column: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub transform_expression: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub default_value: ::core::option::Option<::prost::alloc::string::String>,
}
/// # =============================================================================
/// TextField: Dedicated TEXT storage with strategy hints
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextField {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(enumeration = "TextStorageStrategy", tag = "3")]
    pub storage_hint: i32,
    /// Optional chunking info (populated after storage)
    #[prost(uint32, optional, tag = "10")]
    pub chunk_count: ::core::option::Option<u32>,
    /// Reference to chunks sidecar
    #[prost(string, optional, tag = "11")]
    pub chunk_reference: ::core::option::Option<::prost::alloc::string::String>,
}
/// # =============================================================================
/// ProximaRecord: The new unified record type
///
/// Replaces VectorRecord with:
///
/// * Rich typed columns instead of generic metadata map
/// * Dedicated TEXT fields for chunked text storage
/// * Schema enforcement with catalog integration
/// * Full backward compatibility via flexible_fields
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProximaRecord {
    /// Core identity
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Vector embedding (dense)
    #[prost(float, repeated, tag = "2")]
    pub vector: ::prost::alloc::vec::Vec<f32>,
    /// Explicit dimension for validation
    #[prost(uint32, optional, tag = "3")]
    pub vector_dimension: ::core::option::Option<u32>,
    /// Sparse vector (optional, for hybrid search)
    #[prost(message, optional, tag = "4")]
    pub sparse_vector: ::core::option::Option<SparseVector>,
    /// Typed metadata (validated against schema)
    #[prost(map = "string, message", tag = "5")]
    pub typed_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        TypedValue,
    >,
    /// Flexible overflow (for HYBRID mode or unschematized data)
    /// Uses SqlValue from v1 for backward compatibility
    #[prost(map = "string, message", tag = "6")]
    pub flexible_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::v1::SqlValue,
    >,
    /// TEXT content - dedicated columnar storage
    /// These are stored separately to avoid metadata scanning
    #[prost(message, repeated, tag = "10")]
    pub text_fields: ::prost::alloc::vec::Vec<TextField>,
    /// Temporal fields
    ///
    /// Creation timestamp
    #[prost(int64, tag = "20")]
    pub timestamp_ms: i64,
    /// Last update timestamp
    #[prost(int64, optional, tag = "21")]
    pub updated_at_ms: ::core::option::Option<i64>,
    /// TTL expiration
    #[prost(int64, optional, tag = "22")]
    pub expires_at_ms: ::core::option::Option<i64>,
    /// Optimistic locking version
    #[prost(uint32, optional, tag = "23")]
    pub version: ::core::option::Option<u32>,
    /// Provenance
    ///
    /// Original content reference
    #[prost(string, optional, tag = "30")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    /// MIME type or content type
    #[prost(string, optional, tag = "31")]
    pub source_type: ::core::option::Option<::prost::alloc::string::String>,
    /// Schema this record conforms to
    #[prost(string, optional, tag = "32")]
    pub schema_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Partitioning hints
    #[prost(string, optional, tag = "40")]
    pub partition_key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "41")]
    pub partition_values: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Audit trail
    #[prost(string, optional, tag = "50")]
    pub created_by: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "51")]
    pub updated_by: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "52")]
    pub custom_metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// # =============================================================================
/// Batch operations for ProximaRecord
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProximaRecordBatch {
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub records: ::prost::alloc::vec::Vec<ProximaRecord>,
    /// Schema to validate against
    #[prost(string, optional, tag = "3")]
    pub schema_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "BatchWriteMode", tag = "4")]
    pub write_mode: i32,
    /// Options
    ///
    /// Default: true
    #[prost(bool, tag = "5")]
    pub validate_schema: bool,
    /// Return generated IDs
    #[prost(bool, tag = "6")]
    pub return_ids: bool,
    /// Return per-record errors
    #[prost(bool, tag = "7")]
    pub return_errors: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProximaRecordBatchResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(int64, tag = "2")]
    pub total_processed: i64,
    #[prost(int64, tag = "3")]
    pub success_count: i64,
    #[prost(int64, tag = "4")]
    pub failed_count: i64,
    #[prost(string, repeated, tag = "5")]
    pub inserted_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "6")]
    pub errors: ::prost::alloc::vec::Vec<BatchError>,
    #[prost(int64, tag = "7")]
    pub processing_time_us: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchError {
    #[prost(int32, tag = "1")]
    pub record_index: i32,
    #[prost(string, tag = "2")]
    pub record_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
/// # =============================================================================
/// Search with typed filters
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypedSearchRequest {
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    /// Query vectors
    #[prost(float, repeated, tag = "2")]
    pub query_vector: ::prost::alloc::vec::Vec<f32>,
    #[prost(message, optional, tag = "3")]
    pub query_sparse_vector: ::core::option::Option<SparseVector>,
    /// Search parameters
    #[prost(uint32, tag = "4")]
    pub top_k: u32,
    #[prost(float, optional, tag = "5")]
    pub score_threshold: ::core::option::Option<f32>,
    /// Typed filters (strongly-typed predicates)
    #[prost(message, repeated, tag = "10")]
    pub filters: ::prost::alloc::vec::Vec<TypedFilterCondition>,
    /// AND/OR for combining filters
    #[prost(enumeration = "FilterLogicOperator", optional, tag = "11")]
    pub filter_logic: ::core::option::Option<i32>,
    /// Projection
    #[prost(string, repeated, tag = "20")]
    pub include_fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "21")]
    pub exclude_fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "22")]
    pub include_vector: bool,
    #[prost(bool, tag = "23")]
    pub include_text_fields: bool,
    /// Search hints
    #[prost(string, optional, tag = "30")]
    pub schema_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "31")]
    pub search_hints: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypedFilterCondition {
    #[prost(string, tag = "1")]
    pub field_name: ::prost::alloc::string::String,
    #[prost(enumeration = "TypedFilterOperator", tag = "2")]
    pub operator: i32,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<TypedValue>,
    /// For BETWEEN
    #[prost(message, optional, tag = "4")]
    pub value_upper: ::core::option::Option<TypedValue>,
    /// For IN/NOT_IN
    #[prost(message, repeated, tag = "5")]
    pub value_list: ::prost::alloc::vec::Vec<TypedValue>,
    /// Nested conditions for complex filters
    #[prost(message, repeated, tag = "10")]
    pub nested: ::prost::alloc::vec::Vec<TypedFilterCondition>,
    #[prost(enumeration = "FilterLogicOperator", optional, tag = "11")]
    pub nested_logic: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypedSearchResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<TypedSearchResult>,
    #[prost(int64, tag = "2")]
    pub total_found: i64,
    #[prost(int64, tag = "3")]
    pub search_time_us: i64,
    #[prost(string, optional, tag = "4")]
    pub collection_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "5")]
    pub search_stats: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypedSearchResult {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub score: f64,
    /// Fields (based on projection)
    #[prost(map = "string, message", tag = "3")]
    pub typed_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        TypedValue,
    >,
    #[prost(float, repeated, tag = "4")]
    pub vector: ::prost::alloc::vec::Vec<f32>,
    #[prost(message, repeated, tag = "5")]
    pub text_fields: ::prost::alloc::vec::Vec<TextField>,
    /// Metadata
    #[prost(int64, optional, tag = "10")]
    pub timestamp_ms: ::core::option::Option<i64>,
    #[prost(uint32, optional, tag = "11")]
    pub version: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "12")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
}
/// # =============================================================================
/// Schema management operations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSchemaRequest {
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub schema: ::core::option::Option<RecordSchema>,
    /// Make this the default schema for the collection
    #[prost(bool, tag = "3")]
    pub set_as_default: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSchemaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub schema_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSchemaRequest {
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    /// If not provided, returns default schema
    #[prost(string, optional, tag = "2")]
    pub schema_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSchemaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, optional, tag = "2")]
    pub schema: ::core::option::Option<RecordSchema>,
    #[prost(string, optional, tag = "3")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSchemasRequest {
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "2")]
    pub limit: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub offset: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSchemasResponse {
    #[prost(message, repeated, tag = "1")]
    pub schemas: ::prost::alloc::vec::Vec<RecordSchema>,
    #[prost(int64, tag = "2")]
    pub total_count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvolveSchemaRequest {
    #[prost(string, tag = "1")]
    pub collection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub base_schema_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub new_schema: ::core::option::Option<RecordSchema>,
    /// Validate without applying
    #[prost(bool, tag = "4")]
    pub dry_run: bool,
    /// Migrate existing records to new schema
    #[prost(bool, tag = "5")]
    pub migrate_existing: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvolveSchemaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub new_schema_id: ::prost::alloc::string::String,
    /// In dry_run mode, shows count
    #[prost(int64, tag = "3")]
    pub records_to_migrate: i64,
    #[prost(string, repeated, tag = "4")]
    pub compatibility_warnings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
}
/// # =============================================================================
/// ColumnDataType: Rich data type enum for ProximaRecord columns
///
/// Extends FilterableDataType with enterprise-grade types for OLAP/OLTP workloads.
/// Each type maps to specific Arrow DataType for columnar storage.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ColumnDataType {
    ColumnTypeUnspecified = 0,
    /// Text types
    ///
    /// UTF-8 string, max 64KB default, Arrow Utf8
    Text = 1,
    /// Large text (>64KB), Arrow LargeUtf8, separate storage
    TextLarge = 2,
    /// Numeric types
    ///
    /// i64, Arrow Int64
    Integer = 3,
    /// f64, Arrow Float64
    Float = 4,
    /// Decimal128(38,18) for financial precision
    Decimal = 5,
    /// Boolean
    ///
    /// Arrow Boolean
    Boolean = 6,
    /// Temporal types
    ///
    /// Microseconds since epoch, no timezone, Arrow Timestamp
    Timestamp = 7,
    /// Microseconds with timezone, Arrow TimestampTz
    TimestampTz = 8,
    /// Date32, days since epoch
    Date = 9,
    /// Time64, microseconds since midnight
    Time = 10,
    /// Duration in microseconds
    Duration = 11,
    /// Calendar interval (months, days, nanos)
    Interval = 12,
    /// Identifier types
    ///
    /// RFC 4122 UUID, validated format, stored as FixedSizeBinary(16)
    Uuid = 13,
    /// Binary types
    ///
    /// Raw bytes, max 1MB default, Arrow Binary
    Binary = 14,
    /// Large binary (>1MB), Arrow LargeBinary
    BinaryLarge = 15,
    /// Structured types
    ///
    /// Validated JSON object, Arrow Utf8 with validation
    Json = 16,
    /// Array types (homogeneous)
    ///
    /// List<Utf8>
    ArrayText = 17,
    /// List<Int64>
    ArrayInteger = 18,
    /// List<Float64>
    ArrayFloat = 19,
    /// List<Boolean>
    ArrayBoolean = 20,
    /// List\<FixedSizeBinary(16)>
    ArrayUuid = 21,
    /// Map types
    ///
    /// Map\<Utf8, Utf8>
    MapStringString = 22,
    /// Map\<Utf8, SqlValue> - flexible values
    MapStringAny = 23,
    /// Map\<Utf8, Int64>
    MapStringInteger = 24,
    /// Map\<Utf8, Float64>
    MapStringFloat = 25,
    /// Geospatial (future expansion)
    ///
    /// (lat, lon) pair
    GeoPoint = 26,
    /// List of points forming a polygon
    GeoPolygon = 27,
    /// Vector embedding (native support)
    ///
    /// Dense vector, List<Float32>
    Vector = 28,
    /// Sparse vector with indices
    SparseVector = 29,
}
impl ColumnDataType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ColumnTypeUnspecified => "COLUMN_TYPE_UNSPECIFIED",
            Self::Text => "TEXT",
            Self::TextLarge => "TEXT_LARGE",
            Self::Integer => "INTEGER",
            Self::Float => "FLOAT",
            Self::Decimal => "DECIMAL",
            Self::Boolean => "BOOLEAN",
            Self::Timestamp => "TIMESTAMP",
            Self::TimestampTz => "TIMESTAMP_TZ",
            Self::Date => "DATE",
            Self::Time => "TIME",
            Self::Duration => "DURATION",
            Self::Interval => "INTERVAL",
            Self::Uuid => "UUID",
            Self::Binary => "BINARY",
            Self::BinaryLarge => "BINARY_LARGE",
            Self::Json => "JSON",
            Self::ArrayText => "ARRAY_TEXT",
            Self::ArrayInteger => "ARRAY_INTEGER",
            Self::ArrayFloat => "ARRAY_FLOAT",
            Self::ArrayBoolean => "ARRAY_BOOLEAN",
            Self::ArrayUuid => "ARRAY_UUID",
            Self::MapStringString => "MAP_STRING_STRING",
            Self::MapStringAny => "MAP_STRING_ANY",
            Self::MapStringInteger => "MAP_STRING_INTEGER",
            Self::MapStringFloat => "MAP_STRING_FLOAT",
            Self::GeoPoint => "GEO_POINT",
            Self::GeoPolygon => "GEO_POLYGON",
            Self::Vector => "VECTOR",
            Self::SparseVector => "SPARSE_VECTOR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COLUMN_TYPE_UNSPECIFIED" => Some(Self::ColumnTypeUnspecified),
            "TEXT" => Some(Self::Text),
            "TEXT_LARGE" => Some(Self::TextLarge),
            "INTEGER" => Some(Self::Integer),
            "FLOAT" => Some(Self::Float),
            "DECIMAL" => Some(Self::Decimal),
            "BOOLEAN" => Some(Self::Boolean),
            "TIMESTAMP" => Some(Self::Timestamp),
            "TIMESTAMP_TZ" => Some(Self::TimestampTz),
            "DATE" => Some(Self::Date),
            "TIME" => Some(Self::Time),
            "DURATION" => Some(Self::Duration),
            "INTERVAL" => Some(Self::Interval),
            "UUID" => Some(Self::Uuid),
            "BINARY" => Some(Self::Binary),
            "BINARY_LARGE" => Some(Self::BinaryLarge),
            "JSON" => Some(Self::Json),
            "ARRAY_TEXT" => Some(Self::ArrayText),
            "ARRAY_INTEGER" => Some(Self::ArrayInteger),
            "ARRAY_FLOAT" => Some(Self::ArrayFloat),
            "ARRAY_BOOLEAN" => Some(Self::ArrayBoolean),
            "ARRAY_UUID" => Some(Self::ArrayUuid),
            "MAP_STRING_STRING" => Some(Self::MapStringString),
            "MAP_STRING_ANY" => Some(Self::MapStringAny),
            "MAP_STRING_INTEGER" => Some(Self::MapStringInteger),
            "MAP_STRING_FLOAT" => Some(Self::MapStringFloat),
            "GEO_POINT" => Some(Self::GeoPoint),
            "GEO_POLYGON" => Some(Self::GeoPolygon),
            "VECTOR" => Some(Self::Vector),
            "SPARSE_VECTOR" => Some(Self::SparseVector),
            _ => None,
        }
    }
}
/// Schema enforcement modes
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SchemaEnforcementMode {
    SchemaEnforcementUnspecified = 0,
    /// All columns must match schema exactly
    Strict = 1,
    /// Schema on read, no validation at insert
    Flexible = 2,
    /// Core columns enforced, additional fields allowed in flexible_fields
    Hybrid = 3,
}
impl SchemaEnforcementMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SchemaEnforcementUnspecified => "SCHEMA_ENFORCEMENT_UNSPECIFIED",
            Self::Strict => "STRICT",
            Self::Flexible => "FLEXIBLE",
            Self::Hybrid => "HYBRID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCHEMA_ENFORCEMENT_UNSPECIFIED" => Some(Self::SchemaEnforcementUnspecified),
            "STRICT" => Some(Self::Strict),
            "FLEXIBLE" => Some(Self::Flexible),
            "HYBRID" => Some(Self::Hybrid),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SchemaEvolutionType {
    EvolutionTypeUnspecified = 0,
    /// New column with default
    AddColumn = 1,
    /// Column dropped (data preserved in flexible_fields if HYBRID)
    RemoveColumn = 2,
    /// Column renamed
    RenameColumn = 3,
    /// Type changed with transform
    ChangeType = 4,
    /// Nullable -> required or vice versa
    ChangeNullability = 5,
}
impl SchemaEvolutionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::EvolutionTypeUnspecified => "EVOLUTION_TYPE_UNSPECIFIED",
            Self::AddColumn => "ADD_COLUMN",
            Self::RemoveColumn => "REMOVE_COLUMN",
            Self::RenameColumn => "RENAME_COLUMN",
            Self::ChangeType => "CHANGE_TYPE",
            Self::ChangeNullability => "CHANGE_NULLABILITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVOLUTION_TYPE_UNSPECIFIED" => Some(Self::EvolutionTypeUnspecified),
            "ADD_COLUMN" => Some(Self::AddColumn),
            "REMOVE_COLUMN" => Some(Self::RemoveColumn),
            "RENAME_COLUMN" => Some(Self::RenameColumn),
            "CHANGE_TYPE" => Some(Self::ChangeType),
            "CHANGE_NULLABILITY" => Some(Self::ChangeNullability),
            _ => None,
        }
    }
}
/// TEXT storage strategies
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TextStorageStrategy {
    TextStorageUnspecified = 0,
    /// Store in main Parquet LargeUtf8 column (\<4KB)
    TextInline = 1,
    /// Split into chunks with embeddings (4KB-1MB)
    TextChunked = 2,
    /// Separate sidecar file (>1MB)
    TextSidecar = 3,
    /// Auto-select based on actual size (default)
    TextAdaptive = 4,
}
impl TextStorageStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TextStorageUnspecified => "TEXT_STORAGE_UNSPECIFIED",
            Self::TextInline => "TEXT_INLINE",
            Self::TextChunked => "TEXT_CHUNKED",
            Self::TextSidecar => "TEXT_SIDECAR",
            Self::TextAdaptive => "TEXT_ADAPTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TEXT_STORAGE_UNSPECIFIED" => Some(Self::TextStorageUnspecified),
            "TEXT_INLINE" => Some(Self::TextInline),
            "TEXT_CHUNKED" => Some(Self::TextChunked),
            "TEXT_SIDECAR" => Some(Self::TextSidecar),
            "TEXT_ADAPTIVE" => Some(Self::TextAdaptive),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BatchWriteMode {
    Unspecified = 0,
    /// Fail if ID exists
    Insert = 1,
    /// Insert or update
    Upsert = 2,
    /// Fail if ID doesn't exist
    Update = 3,
    /// Delete by ID
    Delete = 4,
}
impl BatchWriteMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BATCH_WRITE_MODE_UNSPECIFIED",
            Self::Insert => "INSERT",
            Self::Upsert => "UPSERT",
            Self::Update => "UPDATE",
            Self::Delete => "DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BATCH_WRITE_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "INSERT" => Some(Self::Insert),
            "UPSERT" => Some(Self::Upsert),
            "UPDATE" => Some(Self::Update),
            "DELETE" => Some(Self::Delete),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TypedFilterOperator {
    TypedFilterOpUnspecified = 0,
    /// Equality
    ///
    /// ==
    Eq = 1,
    /// !=
    Ne = 2,
    /// Comparison
    ///
    ///
    /// >
    Gt = 3,
    ///
    /// >
    /// > =
    Gte = 4,
    /// \<
    Lt = 5,
    /// \<=
    Lte = 6,
    /// value \<= x \<= value_upper
    Between = 7,
    /// Set membership
    ///
    /// value in list
    In = 10,
    /// value not in list
    NotIn = 11,
    /// String operations
    ///
    /// substring match
    Contains = 20,
    /// prefix match
    StartsWith = 21,
    /// suffix match
    EndsWith = 22,
    /// regex match
    Regex = 23,
    /// SQL LIKE pattern
    Like = 24,
    /// Fulltext
    ///
    /// Fulltext search
    FulltextMatch = 30,
    /// Array operations
    ///
    /// Array contains element
    ArrayContains = 40,
    /// Array contains all elements
    ArrayContainsAll = 41,
    /// Array contains any element
    ArrayContainsAny = 42,
    /// Array length equals
    ArrayLengthEq = 43,
    /// Array length greater than
    ArrayLengthGt = 44,
    /// Null checks
    IsNull = 50,
    IsNotNull = 51,
    /// JSON path
    ///
    /// JSON path exists
    JsonPathExists = 60,
    /// JSON path value match
    JsonPathMatch = 61,
    /// Geospatial
    ///
    /// Point within polygon
    GeoWithin = 70,
    /// Distance from point
    GeoDistance = 71,
}
impl TypedFilterOperator {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TypedFilterOpUnspecified => "TYPED_FILTER_OP_UNSPECIFIED",
            Self::Eq => "EQ",
            Self::Ne => "NE",
            Self::Gt => "GT",
            Self::Gte => "GTE",
            Self::Lt => "LT",
            Self::Lte => "LTE",
            Self::Between => "BETWEEN",
            Self::In => "IN",
            Self::NotIn => "NOT_IN",
            Self::Contains => "CONTAINS",
            Self::StartsWith => "STARTS_WITH",
            Self::EndsWith => "ENDS_WITH",
            Self::Regex => "REGEX",
            Self::Like => "LIKE",
            Self::FulltextMatch => "FULLTEXT_MATCH",
            Self::ArrayContains => "ARRAY_CONTAINS",
            Self::ArrayContainsAll => "ARRAY_CONTAINS_ALL",
            Self::ArrayContainsAny => "ARRAY_CONTAINS_ANY",
            Self::ArrayLengthEq => "ARRAY_LENGTH_EQ",
            Self::ArrayLengthGt => "ARRAY_LENGTH_GT",
            Self::IsNull => "IS_NULL",
            Self::IsNotNull => "IS_NOT_NULL",
            Self::JsonPathExists => "JSON_PATH_EXISTS",
            Self::JsonPathMatch => "JSON_PATH_MATCH",
            Self::GeoWithin => "GEO_WITHIN",
            Self::GeoDistance => "GEO_DISTANCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TYPED_FILTER_OP_UNSPECIFIED" => Some(Self::TypedFilterOpUnspecified),
            "EQ" => Some(Self::Eq),
            "NE" => Some(Self::Ne),
            "GT" => Some(Self::Gt),
            "GTE" => Some(Self::Gte),
            "LT" => Some(Self::Lt),
            "LTE" => Some(Self::Lte),
            "BETWEEN" => Some(Self::Between),
            "IN" => Some(Self::In),
            "NOT_IN" => Some(Self::NotIn),
            "CONTAINS" => Some(Self::Contains),
            "STARTS_WITH" => Some(Self::StartsWith),
            "ENDS_WITH" => Some(Self::EndsWith),
            "REGEX" => Some(Self::Regex),
            "LIKE" => Some(Self::Like),
            "FULLTEXT_MATCH" => Some(Self::FulltextMatch),
            "ARRAY_CONTAINS" => Some(Self::ArrayContains),
            "ARRAY_CONTAINS_ALL" => Some(Self::ArrayContainsAll),
            "ARRAY_CONTAINS_ANY" => Some(Self::ArrayContainsAny),
            "ARRAY_LENGTH_EQ" => Some(Self::ArrayLengthEq),
            "ARRAY_LENGTH_GT" => Some(Self::ArrayLengthGt),
            "IS_NULL" => Some(Self::IsNull),
            "IS_NOT_NULL" => Some(Self::IsNotNull),
            "JSON_PATH_EXISTS" => Some(Self::JsonPathExists),
            "JSON_PATH_MATCH" => Some(Self::JsonPathMatch),
            "GEO_WITHIN" => Some(Self::GeoWithin),
            "GEO_DISTANCE" => Some(Self::GeoDistance),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FilterLogicOperator {
    FilterLogicUnspecified = 0,
    And = 1,
    Or = 2,
    Not = 3,
}
impl FilterLogicOperator {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FilterLogicUnspecified => "FILTER_LOGIC_UNSPECIFIED",
            Self::And => "AND",
            Self::Or => "OR",
            Self::Not => "NOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FILTER_LOGIC_UNSPECIFIED" => Some(Self::FilterLogicUnspecified),
            "AND" => Some(Self::And),
            "OR" => Some(Self::Or),
            "NOT" => Some(Self::Not),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod proxima_record_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// # =============================================================================
    /// gRPC Service definition
    #[derive(Debug, Clone)]
    pub struct ProximaRecordServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ProximaRecordServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ProximaRecordServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ProximaRecordServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ProximaRecordServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Record operations
        pub async fn insert_records(
            &mut self,
            request: impl tonic::IntoRequest<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/InsertRecords",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "InsertRecords"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn upsert_records(
            &mut self,
            request: impl tonic::IntoRequest<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/UpsertRecords",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "UpsertRecords"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_records(
            &mut self,
            request: impl tonic::IntoRequest<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/UpdateRecords",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "UpdateRecords"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_records(
            &mut self,
            request: impl tonic::IntoRequest<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/DeleteRecords",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "DeleteRecords"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Search operations
        pub async fn search(
            &mut self,
            request: impl tonic::IntoRequest<super::TypedSearchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TypedSearchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/Search",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("proximadb.v2.ProximaRecordService", "Search"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::TypedSearchRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TypedSearchResult>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/SearchStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "SearchStream"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Schema operations
        pub async fn create_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/CreateSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "CreateSchema"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/GetSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "GetSchema"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_schemas(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSchemasRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSchemasResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/ListSchemas",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "ListSchemas"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn evolve_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::EvolveSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EvolveSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/proximadb.v2.ProximaRecordService/EvolveSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("proximadb.v2.ProximaRecordService", "EvolveSchema"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod proxima_record_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ProximaRecordServiceServer.
    #[async_trait]
    pub trait ProximaRecordService: std::marker::Send + std::marker::Sync + 'static {
        /// Record operations
        async fn insert_records(
            &self,
            request: tonic::Request<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        >;
        async fn upsert_records(
            &self,
            request: tonic::Request<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        >;
        async fn update_records(
            &self,
            request: tonic::Request<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        >;
        async fn delete_records(
            &self,
            request: tonic::Request<super::ProximaRecordBatch>,
        ) -> std::result::Result<
            tonic::Response<super::ProximaRecordBatchResponse>,
            tonic::Status,
        >;
        /// Search operations
        async fn search(
            &self,
            request: tonic::Request<super::TypedSearchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TypedSearchResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the SearchStream method.
        type SearchStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TypedSearchResult, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn search_stream(
            &self,
            request: tonic::Request<super::TypedSearchRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SearchStreamStream>,
            tonic::Status,
        >;
        /// Schema operations
        async fn create_schema(
            &self,
            request: tonic::Request<super::CreateSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSchemaResponse>,
            tonic::Status,
        >;
        async fn get_schema(
            &self,
            request: tonic::Request<super::GetSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSchemaResponse>,
            tonic::Status,
        >;
        async fn list_schemas(
            &self,
            request: tonic::Request<super::ListSchemasRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSchemasResponse>,
            tonic::Status,
        >;
        async fn evolve_schema(
            &self,
            request: tonic::Request<super::EvolveSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EvolveSchemaResponse>,
            tonic::Status,
        >;
    }
    /// # =============================================================================
    /// gRPC Service definition
    #[derive(Debug)]
    pub struct ProximaRecordServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ProximaRecordServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for ProximaRecordServiceServer<T>
    where
        T: ProximaRecordService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/proximadb.v2.ProximaRecordService/InsertRecords" => {
                    #[allow(non_camel_case_types)]
                    struct InsertRecordsSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::ProximaRecordBatch>
                    for InsertRecordsSvc<T> {
                        type Response = super::ProximaRecordBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProximaRecordBatch>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::insert_records(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InsertRecordsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/UpsertRecords" => {
                    #[allow(non_camel_case_types)]
                    struct UpsertRecordsSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::ProximaRecordBatch>
                    for UpsertRecordsSvc<T> {
                        type Response = super::ProximaRecordBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProximaRecordBatch>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::upsert_records(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpsertRecordsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/UpdateRecords" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateRecordsSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::ProximaRecordBatch>
                    for UpdateRecordsSvc<T> {
                        type Response = super::ProximaRecordBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProximaRecordBatch>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::update_records(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateRecordsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/DeleteRecords" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteRecordsSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::ProximaRecordBatch>
                    for DeleteRecordsSvc<T> {
                        type Response = super::ProximaRecordBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProximaRecordBatch>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::delete_records(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteRecordsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/Search" => {
                    #[allow(non_camel_case_types)]
                    struct SearchSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::TypedSearchRequest>
                    for SearchSvc<T> {
                        type Response = super::TypedSearchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TypedSearchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::search(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/SearchStream" => {
                    #[allow(non_camel_case_types)]
                    struct SearchStreamSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::ServerStreamingService<super::TypedSearchRequest>
                    for SearchStreamSvc<T> {
                        type Response = super::TypedSearchResult;
                        type ResponseStream = T::SearchStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TypedSearchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::search_stream(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchStreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/CreateSchema" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSchemaSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::CreateSchemaRequest>
                    for CreateSchemaSvc<T> {
                        type Response = super::CreateSchemaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateSchemaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::create_schema(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSchemaSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/GetSchema" => {
                    #[allow(non_camel_case_types)]
                    struct GetSchemaSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::GetSchemaRequest>
                    for GetSchemaSvc<T> {
                        type Response = super::GetSchemaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSchemaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::get_schema(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSchemaSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/ListSchemas" => {
                    #[allow(non_camel_case_types)]
                    struct ListSchemasSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::ListSchemasRequest>
                    for ListSchemasSvc<T> {
                        type Response = super::ListSchemasResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListSchemasRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::list_schemas(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSchemasSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/proximadb.v2.ProximaRecordService/EvolveSchema" => {
                    #[allow(non_camel_case_types)]
                    struct EvolveSchemaSvc<T: ProximaRecordService>(pub Arc<T>);
                    impl<
                        T: ProximaRecordService,
                    > tonic::server::UnaryService<super::EvolveSchemaRequest>
                    for EvolveSchemaSvc<T> {
                        type Response = super::EvolveSchemaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EvolveSchemaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ProximaRecordService>::evolve_schema(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EvolveSchemaSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ProximaRecordServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "proximadb.v2.ProximaRecordService";
    impl<T> tonic::server::NamedService for ProximaRecordServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
