# ProximaDB Local Development Configuration
# Uses local filesystem for all storage

[server]
node_id = "proximadb-local-dev"
bind_address = "127.0.0.1"
port = 5678
data_dir = "./data"

[storage]
# Legacy fields (will be removed in future)
data_dirs = ["./data"]
wal_dir = "./data/wal"

# Storage engine configuration
mmap_enabled = true
cache_size_mb = 1024
bloom_filter_bits = 10

[storage.lsm_config]
memtable_size_mb = 32
level_count = 7
compaction_threshold = 4
block_size_kb = 32

# Local filesystem layout
[storage.storage_layout]
node_instance = 1
assignment_strategy = "HashBased"

[[storage.storage_layout.base_paths]]
base_dir = "./data"
instance_id = 1
mount_point = "./"
disk_type = { SataSsd = { max_iops = 50000 } }

[storage.storage_layout.base_paths.capacity_config]
max_wal_size_mb = 1024
metadata_reserved_mb = 256
warning_threshold_percent = 85.0

[storage.storage_layout.temp_config]
use_same_directory = true
temp_suffix = "___temp"
compaction_suffix = "___compaction"
flush_suffix = "___flushed"
cleanup_on_startup = true

[storage.filesystem_config]
enable_write_strategy_cache = true
temp_strategy = "SameDirectory"

[storage.filesystem_config.atomic_config]
enable_local_atomic = true
enable_object_store_atomic = false
cleanup_temp_on_startup = true

# Local filesystem metadata backend
[storage.metadata_backend]
backend_type = "filestore"
storage_url = "file://./data/metadata"
cache_size_mb = 64
flush_interval_secs = 10

[api]
grpc_port = 5679
rest_port = 5678
max_request_size_mb = 32
timeout_seconds = 30
enable_tls = false

[monitoring]
metrics_enabled = true
log_level = "debug"

[consensus]
node_id = 1
cluster_peers = []
election_timeout_ms = 5000
heartbeat_interval_ms = 1000
snapshot_threshold = 1000