# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, Optional, Union, cast

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.delete_record_v2_response import DeleteRecordV2Response
from ...types import UNSET, Response


def _get_kwargs(
    collection_id: str,
    record_id: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/api/v2/collections/{collection_id}/records/{record_id}".format(
            collection_id=collection_id,
            record_id=record_id,
        ),
    }

    return _kwargs


def _parse_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Optional[DeleteRecordV2Response]:
    if response.status_code == 200:
        response_200 = DeleteRecordV2Response.from_dict(response.json())

        return response_200
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Response[DeleteRecordV2Response]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    collection_id: str,
    record_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Response[DeleteRecordV2Response]:
    """Delete a record by ID.

     Delete a single record by writing a tombstone through the rich record path.

    Args:
        collection_id (str):
        record_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[DeleteRecordV2Response]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        record_id=record_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    collection_id: str,
    record_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Optional[DeleteRecordV2Response]:
    """Delete a record by ID.

     Delete a single record by writing a tombstone through the rich record path.

    Args:
        collection_id (str):
        record_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        DeleteRecordV2Response
    """

    return sync_detailed(
        collection_id=collection_id,
        record_id=record_id,
        client=client,
    ).parsed


async def asyncio_detailed(
    collection_id: str,
    record_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Response[DeleteRecordV2Response]:
    """Delete a record by ID.

     Delete a single record by writing a tombstone through the rich record path.

    Args:
        collection_id (str):
        record_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[DeleteRecordV2Response]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        record_id=record_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    collection_id: str,
    record_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Optional[DeleteRecordV2Response]:
    """Delete a record by ID.

     Delete a single record by writing a tombstone through the rich record path.

    Args:
        collection_id (str):
        record_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        DeleteRecordV2Response
    """

    return (
        await asyncio_detailed(
            collection_id=collection_id,
            record_id=record_id,
            client=client,
        )
    ).parsed
