# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, Optional, Union, cast

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.insert_records_request import InsertRecordsRequest
from ...models.insert_records_response import InsertRecordsResponse
from ...types import UNSET, Response


def _get_kwargs(
    collection_id: str,
    *,
    body: InsertRecordsRequest,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/collections/{collection_id}/records/batch".format(
            collection_id=collection_id,
        ),
    }

    _body = body.to_dict()

    _kwargs["json"] = _body
    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Optional[Union[ErrorResponse, InsertRecordsResponse]]:
    if response.status_code == 200:
        response_200 = InsertRecordsResponse.from_dict(response.json())

        return response_200
    if response.status_code == 400:
        response_400 = ErrorResponse.from_dict(response.json())

        return response_400
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Response[Union[ErrorResponse, InsertRecordsResponse]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    collection_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
    body: InsertRecordsRequest,
) -> Response[Union[ErrorResponse, InsertRecordsResponse]]:
    """Insert or upsert ProximaRecord batches.

     Insert ProximaRecords into a collection with typed field support.

    ## Request Body

    See [`InsertRecordsRequest`] for the expected JSON format.

    ## Response

    Returns [`InsertRecordsResponse`] with counts and any errors.

    ## Errors

    - `400 Bad Request`: Invalid request format or validation error
    - `404 Not Found`: Collection does not exist
    - `500 Internal Server Error`: Storage or processing error

    Args:
        collection_id (str):
        body (InsertRecordsRequest): Request to insert ProximaRecords

            ## Example JSON

            ```json
            {
                "records": [
                    {
                        "id": "doc_1",
                        "vector": [0.1, 0.2, 0.3],
                        "props": {
                            "category": "electronics",
                            "price": 299.99,
                            "in_stock": true
                        },
                        "text_fields": [
                            {
                                "name": "description",
                                "content": "A detailed product description...",
                                "storage_hint": "adaptive"
                            }
                        ],
                        "source": "catalog_import"
                    }
                ],
                "validate_schema": true
            }
            ```
            Not supported in v0.2: optimistic versioning, conditional-write predicates,
            update-by-filter, delete-by-filter, and patch / partial-record update. The
            live contract is exposed via `WriteContractHealth` on the route-health
            diagnostic endpoint (`GET /api/v2/_diagnostics/collections/{id}/route-health`);
            see also `docs/SUPPORTED_SURFACE.adoc` "Not Supported in v0.2".

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[ErrorResponse, InsertRecordsResponse]]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    collection_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
    body: InsertRecordsRequest,
) -> Optional[Union[ErrorResponse, InsertRecordsResponse]]:
    """Insert or upsert ProximaRecord batches.

     Insert ProximaRecords into a collection with typed field support.

    ## Request Body

    See [`InsertRecordsRequest`] for the expected JSON format.

    ## Response

    Returns [`InsertRecordsResponse`] with counts and any errors.

    ## Errors

    - `400 Bad Request`: Invalid request format or validation error
    - `404 Not Found`: Collection does not exist
    - `500 Internal Server Error`: Storage or processing error

    Args:
        collection_id (str):
        body (InsertRecordsRequest): Request to insert ProximaRecords

            ## Example JSON

            ```json
            {
                "records": [
                    {
                        "id": "doc_1",
                        "vector": [0.1, 0.2, 0.3],
                        "props": {
                            "category": "electronics",
                            "price": 299.99,
                            "in_stock": true
                        },
                        "text_fields": [
                            {
                                "name": "description",
                                "content": "A detailed product description...",
                                "storage_hint": "adaptive"
                            }
                        ],
                        "source": "catalog_import"
                    }
                ],
                "validate_schema": true
            }
            ```
            Not supported in v0.2: optimistic versioning, conditional-write predicates,
            update-by-filter, delete-by-filter, and patch / partial-record update. The
            live contract is exposed via `WriteContractHealth` on the route-health
            diagnostic endpoint (`GET /api/v2/_diagnostics/collections/{id}/route-health`);
            see also `docs/SUPPORTED_SURFACE.adoc` "Not Supported in v0.2".

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[ErrorResponse, InsertRecordsResponse]
    """

    return sync_detailed(
        collection_id=collection_id,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    collection_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
    body: InsertRecordsRequest,
) -> Response[Union[ErrorResponse, InsertRecordsResponse]]:
    """Insert or upsert ProximaRecord batches.

     Insert ProximaRecords into a collection with typed field support.

    ## Request Body

    See [`InsertRecordsRequest`] for the expected JSON format.

    ## Response

    Returns [`InsertRecordsResponse`] with counts and any errors.

    ## Errors

    - `400 Bad Request`: Invalid request format or validation error
    - `404 Not Found`: Collection does not exist
    - `500 Internal Server Error`: Storage or processing error

    Args:
        collection_id (str):
        body (InsertRecordsRequest): Request to insert ProximaRecords

            ## Example JSON

            ```json
            {
                "records": [
                    {
                        "id": "doc_1",
                        "vector": [0.1, 0.2, 0.3],
                        "props": {
                            "category": "electronics",
                            "price": 299.99,
                            "in_stock": true
                        },
                        "text_fields": [
                            {
                                "name": "description",
                                "content": "A detailed product description...",
                                "storage_hint": "adaptive"
                            }
                        ],
                        "source": "catalog_import"
                    }
                ],
                "validate_schema": true
            }
            ```
            Not supported in v0.2: optimistic versioning, conditional-write predicates,
            update-by-filter, delete-by-filter, and patch / partial-record update. The
            live contract is exposed via `WriteContractHealth` on the route-health
            diagnostic endpoint (`GET /api/v2/_diagnostics/collections/{id}/route-health`);
            see also `docs/SUPPORTED_SURFACE.adoc` "Not Supported in v0.2".

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[ErrorResponse, InsertRecordsResponse]]
    """

    kwargs = _get_kwargs(
        collection_id=collection_id,
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    collection_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
    body: InsertRecordsRequest,
) -> Optional[Union[ErrorResponse, InsertRecordsResponse]]:
    """Insert or upsert ProximaRecord batches.

     Insert ProximaRecords into a collection with typed field support.

    ## Request Body

    See [`InsertRecordsRequest`] for the expected JSON format.

    ## Response

    Returns [`InsertRecordsResponse`] with counts and any errors.

    ## Errors

    - `400 Bad Request`: Invalid request format or validation error
    - `404 Not Found`: Collection does not exist
    - `500 Internal Server Error`: Storage or processing error

    Args:
        collection_id (str):
        body (InsertRecordsRequest): Request to insert ProximaRecords

            ## Example JSON

            ```json
            {
                "records": [
                    {
                        "id": "doc_1",
                        "vector": [0.1, 0.2, 0.3],
                        "props": {
                            "category": "electronics",
                            "price": 299.99,
                            "in_stock": true
                        },
                        "text_fields": [
                            {
                                "name": "description",
                                "content": "A detailed product description...",
                                "storage_hint": "adaptive"
                            }
                        ],
                        "source": "catalog_import"
                    }
                ],
                "validate_schema": true
            }
            ```
            Not supported in v0.2: optimistic versioning, conditional-write predicates,
            update-by-filter, delete-by-filter, and patch / partial-record update. The
            live contract is exposed via `WriteContractHealth` on the route-health
            diagnostic endpoint (`GET /api/v2/_diagnostics/collections/{id}/route-health`);
            see also `docs/SUPPORTED_SURFACE.adoc` "Not Supported in v0.2".

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[ErrorResponse, InsertRecordsResponse]
    """

    return (
        await asyncio_detailed(
            collection_id=collection_id,
            client=client,
            body=body,
        )
    ).parsed
