# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from proximadb.v2 import graph_pb2 as proximadb_dot_v2_dot_graph__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in proximadb/v2/graph_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ProximaGraphServiceStub(object):
    """============================================================================
    Service
    ============================================================================

    Canonical v2 graph service. Replaces the deprecated
    `proximadb.v1.GraphService` for SDK and external clients.

    Deferred from this first surface (tracked as a follow-up TD; still reachable
    on v1 behind `enable_grpc_v1_compat`): StreamTraverse, GetConnectedComponents,
    HasCycle, Add/RemoveUniqueConstraint, BatchCreateNodes/Edges, ExecuteQuery
    (Cypher/Gremlin), ExecuteHybridQuery, and the retired PULSAR/QUASAR RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNode = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/CreateNode",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.CreateGraphNodeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.FromString,
            _registered_method=True,
        )
        self.GetNode = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/GetNode",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.GetGraphNodeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.FromString,
            _registered_method=True,
        )
        self.UpdateNode = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/UpdateNode",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.UpdateGraphNodeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.FromString,
            _registered_method=True,
        )
        self.DeleteNode = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/DeleteNode",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphNodeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphNodeResponse.FromString,
            _registered_method=True,
        )
        self.CreateEdge = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/CreateEdge",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.CreateGraphEdgeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.FromString,
            _registered_method=True,
        )
        self.GetEdge = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/GetEdge",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.GetGraphEdgeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.FromString,
            _registered_method=True,
        )
        self.UpdateEdge = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/UpdateEdge",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.UpdateGraphEdgeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.FromString,
            _registered_method=True,
        )
        self.DeleteEdge = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/DeleteEdge",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphEdgeRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphEdgeResponse.FromString,
            _registered_method=True,
        )
        self.QueryNodes = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/QueryNodes",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphNodesRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphNodesResponse.FromString,
            _registered_method=True,
        )
        self.QueryEdges = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/QueryEdges",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphEdgesRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphEdgesResponse.FromString,
            _registered_method=True,
        )
        self.GetNeighbors = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/GetNeighbors",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.GetGraphNeighborsRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GetGraphNeighborsResponse.FromString,
            _registered_method=True,
        )
        self.TraverseGraph = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/TraverseGraph",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.TraverseGraphRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.TraverseGraphResponse.FromString,
            _registered_method=True,
        )
        self.ShortestPath = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/ShortestPath",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.GraphShortestPathRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphShortestPathResponse.FromString,
            _registered_method=True,
        )
        self.GetGraphStats = channel.unary_unary(
            "/proximadb.v2.ProximaGraphService/GetGraphStats",
            request_serializer=proximadb_dot_v2_dot_graph__pb2.GetGraphStatsRequest.SerializeToString,
            response_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphStats.FromString,
            _registered_method=True,
        )


class ProximaGraphServiceServicer(object):
    """============================================================================
    Service
    ============================================================================

    Canonical v2 graph service. Replaces the deprecated
    `proximadb.v1.GraphService` for SDK and external clients.

    Deferred from this first surface (tracked as a follow-up TD; still reachable
    on v1 behind `enable_grpc_v1_compat`): StreamTraverse, GetConnectedComponents,
    HasCycle, Add/RemoveUniqueConstraint, BatchCreateNodes/Edges, ExecuteQuery
    (Cypher/Gremlin), ExecuteHybridQuery, and the retired PULSAR/QUASAR RPCs.
    """

    def CreateNode(self, request, context):
        """Node operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateEdge(self, request, context):
        """Edge operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryNodes(self, request, context):
        """Query operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNeighbors(self, request, context):
        """Graph operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TraverseGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ShortestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetGraphStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProximaGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateNode": grpc.unary_unary_rpc_method_handler(
            servicer.CreateNode,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.CreateGraphNodeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.SerializeToString,
        ),
        "GetNode": grpc.unary_unary_rpc_method_handler(
            servicer.GetNode,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.GetGraphNodeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.SerializeToString,
        ),
        "UpdateNode": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateNode,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.UpdateGraphNodeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.SerializeToString,
        ),
        "DeleteNode": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteNode,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphNodeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphNodeResponse.SerializeToString,
        ),
        "CreateEdge": grpc.unary_unary_rpc_method_handler(
            servicer.CreateEdge,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.CreateGraphEdgeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.SerializeToString,
        ),
        "GetEdge": grpc.unary_unary_rpc_method_handler(
            servicer.GetEdge,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.GetGraphEdgeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.SerializeToString,
        ),
        "UpdateEdge": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateEdge,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.UpdateGraphEdgeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.SerializeToString,
        ),
        "DeleteEdge": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteEdge,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphEdgeRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.DeleteGraphEdgeResponse.SerializeToString,
        ),
        "QueryNodes": grpc.unary_unary_rpc_method_handler(
            servicer.QueryNodes,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphNodesRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphNodesResponse.SerializeToString,
        ),
        "QueryEdges": grpc.unary_unary_rpc_method_handler(
            servicer.QueryEdges,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphEdgesRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.QueryGraphEdgesResponse.SerializeToString,
        ),
        "GetNeighbors": grpc.unary_unary_rpc_method_handler(
            servicer.GetNeighbors,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.GetGraphNeighborsRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GetGraphNeighborsResponse.SerializeToString,
        ),
        "TraverseGraph": grpc.unary_unary_rpc_method_handler(
            servicer.TraverseGraph,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.TraverseGraphRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.TraverseGraphResponse.SerializeToString,
        ),
        "ShortestPath": grpc.unary_unary_rpc_method_handler(
            servicer.ShortestPath,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.GraphShortestPathRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphShortestPathResponse.SerializeToString,
        ),
        "GetGraphStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetGraphStats,
            request_deserializer=proximadb_dot_v2_dot_graph__pb2.GetGraphStatsRequest.FromString,
            response_serializer=proximadb_dot_v2_dot_graph__pb2.GraphStats.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proximadb.v2.ProximaGraphService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "proximadb.v2.ProximaGraphService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ProximaGraphService(object):
    """============================================================================
    Service
    ============================================================================

    Canonical v2 graph service. Replaces the deprecated
    `proximadb.v1.GraphService` for SDK and external clients.

    Deferred from this first surface (tracked as a follow-up TD; still reachable
    on v1 behind `enable_grpc_v1_compat`): StreamTraverse, GetConnectedComponents,
    HasCycle, Add/RemoveUniqueConstraint, BatchCreateNodes/Edges, ExecuteQuery
    (Cypher/Gremlin), ExecuteHybridQuery, and the retired PULSAR/QUASAR RPCs.
    """

    @staticmethod
    def CreateNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/CreateNode",
            proximadb_dot_v2_dot_graph__pb2.CreateGraphNodeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/GetNode",
            proximadb_dot_v2_dot_graph__pb2.GetGraphNodeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/UpdateNode",
            proximadb_dot_v2_dot_graph__pb2.UpdateGraphNodeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/DeleteNode",
            proximadb_dot_v2_dot_graph__pb2.DeleteGraphNodeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.DeleteGraphNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/CreateEdge",
            proximadb_dot_v2_dot_graph__pb2.CreateGraphEdgeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/GetEdge",
            proximadb_dot_v2_dot_graph__pb2.GetGraphEdgeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/UpdateEdge",
            proximadb_dot_v2_dot_graph__pb2.UpdateGraphEdgeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/DeleteEdge",
            proximadb_dot_v2_dot_graph__pb2.DeleteGraphEdgeRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.DeleteGraphEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryNodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/QueryNodes",
            proximadb_dot_v2_dot_graph__pb2.QueryGraphNodesRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.QueryGraphNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryEdges(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/QueryEdges",
            proximadb_dot_v2_dot_graph__pb2.QueryGraphEdgesRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.QueryGraphEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNeighbors(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/GetNeighbors",
            proximadb_dot_v2_dot_graph__pb2.GetGraphNeighborsRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GetGraphNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TraverseGraph(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/TraverseGraph",
            proximadb_dot_v2_dot_graph__pb2.TraverseGraphRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.TraverseGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ShortestPath(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/ShortestPath",
            proximadb_dot_v2_dot_graph__pb2.GraphShortestPathRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphShortestPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetGraphStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proximadb.v2.ProximaGraphService/GetGraphStats",
            proximadb_dot_v2_dot_graph__pb2.GetGraphStatsRequest.SerializeToString,
            proximadb_dot_v2_dot_graph__pb2.GraphStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
