# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.health_response import HealthResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/health",
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> HealthResponse | None:
    if response.status_code == 200:
        response_200 = HealthResponse.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[HealthResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[HealthResponse]:
    """Get server health.

    Args:
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HealthResponse]
    """

    kwargs = _get_kwargs(
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> HealthResponse | None:
    """Get server health.

    Args:
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HealthResponse
    """

    return sync_detailed(
        client=client,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> Response[HealthResponse]:
    """Get server health.

    Args:
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HealthResponse]
    """

    kwargs = _get_kwargs(
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    x_tenant_id: str | Unset = UNSET,
) -> HealthResponse | None:
    """Get server health.

    Args:
        x_tenant_id (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HealthResponse
    """

    return (
        await asyncio_detailed(
            client=client,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
