# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.abac_attribute_binding import AbacAttributeBinding
from ...models.abac_operator_error_response import AbacOperatorErrorResponse
from ...models.abac_post_attribute_binding_request import (
    AbacPostAttributeBindingRequest,
)
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: AbacPostAttributeBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v2/abac/attribute-bindings",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> AbacAttributeBinding | AbacOperatorErrorResponse | None:
    if response.status_code == 200:
        response_200 = AbacAttributeBinding.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_403

    if response.status_code == 422:
        response_422 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_422

    if response.status_code == 503:
        response_503 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[AbacAttributeBinding | AbacOperatorErrorResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: AbacPostAttributeBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> Response[AbacAttributeBinding | AbacOperatorErrorResponse]:
    """Upsert a subject's ABAC attribute binding.

     The authority half of ABAC — a `(subject, tenant)`-keyed,
    multi-valued attribute set a policy's `predicate_ref` resolves
    against. Writes through the same store the live enforcer reads.

    Args:
        x_tenant_id (str | Unset):
        body (AbacPostAttributeBindingRequest): Body for `POST /api/v2/abac/attribute-bindings`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AbacAttributeBinding | AbacOperatorErrorResponse]
    """

    kwargs = _get_kwargs(
        body=body,
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: AbacPostAttributeBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> AbacAttributeBinding | AbacOperatorErrorResponse | None:
    """Upsert a subject's ABAC attribute binding.

     The authority half of ABAC — a `(subject, tenant)`-keyed,
    multi-valued attribute set a policy's `predicate_ref` resolves
    against. Writes through the same store the live enforcer reads.

    Args:
        x_tenant_id (str | Unset):
        body (AbacPostAttributeBindingRequest): Body for `POST /api/v2/abac/attribute-bindings`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AbacAttributeBinding | AbacOperatorErrorResponse
    """

    return sync_detailed(
        client=client,
        body=body,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: AbacPostAttributeBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> Response[AbacAttributeBinding | AbacOperatorErrorResponse]:
    """Upsert a subject's ABAC attribute binding.

     The authority half of ABAC — a `(subject, tenant)`-keyed,
    multi-valued attribute set a policy's `predicate_ref` resolves
    against. Writes through the same store the live enforcer reads.

    Args:
        x_tenant_id (str | Unset):
        body (AbacPostAttributeBindingRequest): Body for `POST /api/v2/abac/attribute-bindings`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AbacAttributeBinding | AbacOperatorErrorResponse]
    """

    kwargs = _get_kwargs(
        body=body,
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: AbacPostAttributeBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> AbacAttributeBinding | AbacOperatorErrorResponse | None:
    """Upsert a subject's ABAC attribute binding.

     The authority half of ABAC — a `(subject, tenant)`-keyed,
    multi-valued attribute set a policy's `predicate_ref` resolves
    against. Writes through the same store the live enforcer reads.

    Args:
        x_tenant_id (str | Unset):
        body (AbacPostAttributeBindingRequest): Body for `POST /api/v2/abac/attribute-bindings`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AbacAttributeBinding | AbacOperatorErrorResponse
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
