# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.abac_operator_error_response import AbacOperatorErrorResponse
from ...models.abac_policy_binding import AbacPolicyBinding
from ...models.abac_put_policy_binding_request import AbacPutPolicyBindingRequest
from ...types import UNSET, Response, Unset


def _get_kwargs(
    tenant: str,
    object_id: int,
    *,
    body: AbacPutPolicyBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_tenant_id, Unset):
        headers["X-Tenant-ID"] = x_tenant_id

    _kwargs: dict[str, Any] = {
        "method": "put",
        "url": "/api/v2/abac/policy-bindings/{tenant}/{object_id}".format(
            tenant=quote(str(tenant), safe=""),
            object_id=quote(str(object_id), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> AbacOperatorErrorResponse | AbacPolicyBinding | None:
    if response.status_code == 200:
        response_200 = AbacPolicyBinding.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_403

    if response.status_code == 422:
        response_422 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_422

    if response.status_code == 503:
        response_503 = AbacOperatorErrorResponse.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[AbacOperatorErrorResponse | AbacPolicyBinding]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    tenant: str,
    object_id: int,
    *,
    client: AuthenticatedClient | Client,
    body: AbacPutPolicyBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> Response[AbacOperatorErrorResponse | AbacPolicyBinding]:
    """Upsert an ABAC policy binding.

     Provisions (or replaces) the policy binding at `object_id` for
    `tenant` — a constraint-layer rule (`scope` + `effect`, optionally a
    `predicate_ref` row filter and a `field_mask`). Writes through the
    same store the live enforcer reads: visible on the next request, no
    restart. `Deny` wins during resolution; the default is deny.
    The optional `X-Tenant-ID` header is not consulted by this
    handler — the tenant path segment governs.

    Args:
        tenant (str):
        object_id (int):
        x_tenant_id (str | Unset):
        body (AbacPutPolicyBindingRequest): Body for `PUT /api/v2/abac/policy-
            bindings/{tenant}/{object_id}`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AbacOperatorErrorResponse | AbacPolicyBinding]
    """

    kwargs = _get_kwargs(
        tenant=tenant,
        object_id=object_id,
        body=body,
        x_tenant_id=x_tenant_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    tenant: str,
    object_id: int,
    *,
    client: AuthenticatedClient | Client,
    body: AbacPutPolicyBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> AbacOperatorErrorResponse | AbacPolicyBinding | None:
    """Upsert an ABAC policy binding.

     Provisions (or replaces) the policy binding at `object_id` for
    `tenant` — a constraint-layer rule (`scope` + `effect`, optionally a
    `predicate_ref` row filter and a `field_mask`). Writes through the
    same store the live enforcer reads: visible on the next request, no
    restart. `Deny` wins during resolution; the default is deny.
    The optional `X-Tenant-ID` header is not consulted by this
    handler — the tenant path segment governs.

    Args:
        tenant (str):
        object_id (int):
        x_tenant_id (str | Unset):
        body (AbacPutPolicyBindingRequest): Body for `PUT /api/v2/abac/policy-
            bindings/{tenant}/{object_id}`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AbacOperatorErrorResponse | AbacPolicyBinding
    """

    return sync_detailed(
        tenant=tenant,
        object_id=object_id,
        client=client,
        body=body,
        x_tenant_id=x_tenant_id,
    ).parsed


async def asyncio_detailed(
    tenant: str,
    object_id: int,
    *,
    client: AuthenticatedClient | Client,
    body: AbacPutPolicyBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> Response[AbacOperatorErrorResponse | AbacPolicyBinding]:
    """Upsert an ABAC policy binding.

     Provisions (or replaces) the policy binding at `object_id` for
    `tenant` — a constraint-layer rule (`scope` + `effect`, optionally a
    `predicate_ref` row filter and a `field_mask`). Writes through the
    same store the live enforcer reads: visible on the next request, no
    restart. `Deny` wins during resolution; the default is deny.
    The optional `X-Tenant-ID` header is not consulted by this
    handler — the tenant path segment governs.

    Args:
        tenant (str):
        object_id (int):
        x_tenant_id (str | Unset):
        body (AbacPutPolicyBindingRequest): Body for `PUT /api/v2/abac/policy-
            bindings/{tenant}/{object_id}`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AbacOperatorErrorResponse | AbacPolicyBinding]
    """

    kwargs = _get_kwargs(
        tenant=tenant,
        object_id=object_id,
        body=body,
        x_tenant_id=x_tenant_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    tenant: str,
    object_id: int,
    *,
    client: AuthenticatedClient | Client,
    body: AbacPutPolicyBindingRequest,
    x_tenant_id: str | Unset = UNSET,
) -> AbacOperatorErrorResponse | AbacPolicyBinding | None:
    """Upsert an ABAC policy binding.

     Provisions (or replaces) the policy binding at `object_id` for
    `tenant` — a constraint-layer rule (`scope` + `effect`, optionally a
    `predicate_ref` row filter and a `field_mask`). Writes through the
    same store the live enforcer reads: visible on the next request, no
    restart. `Deny` wins during resolution; the default is deny.
    The optional `X-Tenant-ID` header is not consulted by this
    handler — the tenant path segment governs.

    Args:
        tenant (str):
        object_id (int):
        x_tenant_id (str | Unset):
        body (AbacPutPolicyBindingRequest): Body for `PUT /api/v2/abac/policy-
            bindings/{tenant}/{object_id}`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AbacOperatorErrorResponse | AbacPolicyBinding
    """

    return (
        await asyncio_detailed(
            tenant=tenant,
            object_id=object_id,
            client=client,
            body=body,
            x_tenant_id=x_tenant_id,
        )
    ).parsed
