# @generated by openapi-python-client (TD-126 Phase 4) — DO NOT EDIT.
#
# Regenerate with `make gen-python-sdk`. Source of truth:
# docs/openapi/proximadb-openapi.yaml. The CI gate `python-sdk-codegen-drift`
# fails if this directory drifts from a fresh regeneration.
from http import HTTPStatus
from typing import Any, Optional, Union, cast

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.graph_stats_response import GraphStatsResponse
from ...types import UNSET, Response


def _get_kwargs(
    graph_id: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v2/graphs/{graph_id}/stats".format(
            graph_id=graph_id,
        ),
    }

    return _kwargs


def _parse_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Optional[GraphStatsResponse]:
    if response.status_code == 200:
        response_200 = GraphStatsResponse.from_dict(response.json())

        return response_200
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Response[GraphStatsResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    graph_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Response[GraphStatsResponse]:
    """Get graph statistics.

    Args:
        graph_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GraphStatsResponse]
    """

    kwargs = _get_kwargs(
        graph_id=graph_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    graph_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Optional[GraphStatsResponse]:
    """Get graph statistics.

    Args:
        graph_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GraphStatsResponse
    """

    return sync_detailed(
        graph_id=graph_id,
        client=client,
    ).parsed


async def asyncio_detailed(
    graph_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Response[GraphStatsResponse]:
    """Get graph statistics.

    Args:
        graph_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GraphStatsResponse]
    """

    kwargs = _get_kwargs(
        graph_id=graph_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    graph_id: str,
    *,
    client: Union[AuthenticatedClient, Client],
) -> Optional[GraphStatsResponse]:
    """Get graph statistics.

    Args:
        graph_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GraphStatsResponse
    """

    return (
        await asyncio_detailed(
            graph_id=graph_id,
            client=client,
        )
    ).parsed
