apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proximadb

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: proximadb
  app.kubernetes.io/instance: default
  app.kubernetes.io/managed-by: kustomize

images:
  - name: proximadb/proximadb
    newTag: "0.1.4"
